/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GoalId = IDL.Nat;
export const ObstacleTemplateId = IDL.Nat;
export const CreateHabitRequest = IDL.Record({
  'startTime' : IDL.Opt(IDL.Text),
  'endTimeMinutes' : IDL.Opt(IDL.Nat),
  'endTime' : IDL.Opt(IDL.Text),
  'scheduledDays' : IDL.Opt(IDL.Vec(IDL.Text)),
  'startTimeMinutes' : IDL.Opt(IDL.Nat),
  'goalId' : GoalId,
  'themeColor' : IDL.Opt(IDL.Text),
  'wishDescription' : IDL.Opt(IDL.Text),
  'iconName' : IDL.Opt(IDL.Text),
  'ifThenPlan' : IDL.Text,
  'obstacleTemplateId' : IDL.Opt(ObstacleTemplateId),
  'isLockIn' : IDL.Bool,
  'lockInDurationMinutes' : IDL.Opt(IDL.Nat),
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const GoalState = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'paused' : IDL.Null,
});
export const GoalCategory = IDL.Variant({
  'Productivity' : IDL.Null,
  'Learning' : IDL.Null,
  'Health' : IDL.Null,
  'Social' : IDL.Null,
  'Leisure' : IDL.Null,
});
export const HabitPublic = IDL.Record({
  'id' : GoalId,
  'startTime' : IDL.Opt(IDL.Text),
  'endTimeMinutes' : IDL.Nat,
  'endTime' : IDL.Opt(IDL.Text),
  'scheduledDays' : IDL.Vec(IDL.Text),
  'owner' : UserId,
  'lastEditedAt' : IDL.Opt(Timestamp),
  'startTimeMinutes' : IDL.Nat,
  'createdAt' : Timestamp,
  'wish' : IDL.Text,
  'goalId' : GoalId,
  'themeColor' : IDL.Opt(IDL.Text),
  'wishDescription' : IDL.Text,
  'iconName' : IDL.Opt(IDL.Text),
  'ifThenPlan' : IDL.Text,
  'updatedAt' : Timestamp,
  'state' : GoalState,
  'obstacleTemplateId' : IDL.Opt(ObstacleTemplateId),
  'category' : GoalCategory,
  'isLockIn' : IDL.Bool,
  'outcome' : IDL.Text,
  'lockInDurationMinutes' : IDL.Nat,
});
export const CreateMacroGoalRequest = IDL.Record({
  'wish' : IDL.Text,
  'themeColor' : IDL.Opt(IDL.Text),
  'wishDescription' : IDL.Text,
  'iconName' : IDL.Opt(IDL.Text),
  'category' : GoalCategory,
  'outcome' : IDL.Text,
});
export const MacroGoalPublic = IDL.Record({
  'id' : GoalId,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'wish' : IDL.Text,
  'themeColor' : IDL.Opt(IDL.Text),
  'wishDescription' : IDL.Text,
  'iconName' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'state' : GoalState,
  'category' : GoalCategory,
  'outcome' : IDL.Text,
});
export const CreateObstacleRequest = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const ObstacleTemplate = IDL.Record({
  'id' : ObstacleTemplateId,
  'title' : IDL.Text,
  'owner' : UserId,
  'description' : IDL.Text,
});
export const CheckInId = IDL.Nat;
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const GoalAnalytics = IDL.Record({
  'totalMissed' : IDL.Nat,
  'completionRate' : IDL.Float64,
  'goalName' : IDL.Text,
  'goalId' : GoalId,
  'totalSkips' : IDL.Nat,
  'longestStreak' : IDL.Nat,
  'totalSuccesses' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const AnalyticsSummary = IDL.Record({
  'goals' : IDL.Vec(GoalAnalytics),
  'dailySuccessRate30Days' : IDL.Vec(IDL.Float64),
});
export const CheckInType = IDL.Variant({
  'skip' : IDL.Null,
  'missedCheckIn' : IDL.Null,
  'missedCheckOut' : IDL.Null,
  'success' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const CheckIn = IDL.Record({
  'id' : CheckInId,
  'owner' : UserId,
  'goalId' : GoalId,
  'checkInType' : CheckInType,
  'obstacleTemplateId' : IDL.Opt(ObstacleTemplateId),
  'timestamp' : Timestamp,
  'executedIfThen' : IDL.Bool,
  'lockInStartedAt' : IDL.Opt(IDL.Int),
  'lockInEndedAt' : IDL.Opt(IDL.Int),
  'customObstacleNote' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const AvatarColor = IDL.Opt(IDL.Text);
export const AvatarColorMode = IDL.Variant({
  'Fill' : IDL.Null,
  'BorderOnly' : IDL.Null,
});
export const AvatarShape = IDL.Opt(
  IDL.Variant({
    'Star' : IDL.Null,
    'Pentagon' : IDL.Null,
    'Triangle' : IDL.Null,
    'Hexagon' : IDL.Null,
    'Square' : IDL.Null,
  })
);
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Opt(IDL.Text),
  'timezone' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'timezoneOffsetMinutes' : IDL.Int,
  'role' : UserRole,
  'email' : IDL.Opt(IDL.Text),
  'avatarColor' : AvatarColor,
  'avatarColorMode' : AvatarColorMode,
  'avatarShape' : AvatarShape,
});
export const FeedItem = IDL.Record({
  'checkIn' : CheckIn,
  'goalName' : IDL.Text,
  'partnerDisplayName' : IDL.Text,
  'partnerAvatarColor' : AvatarColor,
  'highFiveCount' : IDL.Nat,
  'partnerAvatarColorMode' : AvatarColorMode,
  'partnerAvatarShape' : AvatarShape,
});
export const PartnerHabitDetail = IDL.Record({
  'habits' : IDL.Vec(HabitPublic),
  'profile' : UserProfilePublic,
});
export const PartnerHabitError = IDL.Variant({
  'notPartner' : IDL.Null,
  'profileNotFound' : IDL.Null,
});
export const ConnectionId = IDL.Nat;
export const ConnectionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const ConnectionPublic = IDL.Record({
  'id' : ConnectionId,
  'status' : ConnectionStatus,
  'createdAt' : Timestamp,
  'toPrincipal' : UserId,
  'fromPrincipal' : UserId,
});
export const GoalWithHabitsPublic = IDL.Record({
  'goal' : MacroGoalPublic,
  'habits' : IDL.Vec(HabitPublic),
});
export const ReusableGoalPublic = IDL.Record({
  'id' : GoalId,
  'wish' : IDL.Text,
  'wishDescription' : IDL.Text,
  'state' : GoalState,
  'category' : GoalCategory,
});
export const PartnerOverview = IDL.Record({
  'activeHabitCount' : IDL.Nat,
  'profile' : UserProfilePublic,
  'currentStreak' : IDL.Nat,
});
export const RecordCheckInRequest = IDL.Record({
  'timezoneOffsetMinutes' : IDL.Int,
  'goalId' : GoalId,
  'checkInType' : CheckInType,
  'obstacleTemplateId' : IDL.Opt(ObstacleTemplateId),
  'executedIfThen' : IDL.Bool,
  'lockInStartedAt' : IDL.Opt(IDL.Int),
  'lockInEndedAt' : IDL.Opt(IDL.Int),
  'customObstacleNote' : IDL.Opt(IDL.Text),
});
export const InteractionType = IDL.Variant({ 'highFive' : IDL.Null });
export const InteractionId = IDL.Nat;
export const Interaction = IDL.Record({
  'id' : InteractionId,
  'interactionType' : InteractionType,
  'fromPrincipal' : UserId,
  'checkInId' : CheckInId,
  'timestamp' : Timestamp,
});
export const UpdateHabitRequest = IDL.Record({
  'startTime' : IDL.Opt(IDL.Text),
  'endTimeMinutes' : IDL.Opt(IDL.Nat),
  'endTime' : IDL.Opt(IDL.Text),
  'scheduledDays' : IDL.Opt(IDL.Vec(IDL.Text)),
  'timezoneOffsetMinutes' : IDL.Int,
  'startTimeMinutes' : IDL.Opt(IDL.Nat),
  'themeColor' : IDL.Opt(IDL.Text),
  'isTimeEdit' : IDL.Opt(IDL.Bool),
  'iconName' : IDL.Opt(IDL.Text),
  'ifThenPlan' : IDL.Opt(IDL.Text),
  'isLockIn' : IDL.Opt(IDL.Bool),
  'lockInDurationMinutes' : IDL.Opt(IDL.Nat),
});
export const UpdateMacroGoalRequest = IDL.Record({
  'themeColor' : IDL.Opt(IDL.Text),
  'iconName' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'createHabit' : IDL.Func(
      [CreateHabitRequest],
      [IDL.Variant({ 'ok' : HabitPublic, 'err' : IDL.Text })],
      [],
    ),
  'createMacroGoal' : IDL.Func(
      [CreateMacroGoalRequest],
      [IDL.Variant({ 'ok' : MacroGoalPublic, 'err' : IDL.Text })],
      [],
    ),
  'createObstacleTemplate' : IDL.Func(
      [CreateObstacleRequest],
      [ObstacleTemplate],
      [],
    ),
  'deleteCheckIn' : IDL.Func(
      [CheckInId],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'err' : IDL.Variant({
            'sealed' : IDL.Text,
            'notFound' : IDL.Null,
            'unauthorized' : IDL.Null,
          }),
        }),
      ],
      [],
    ),
  'deleteGoal' : IDL.Func(
      [GoalId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteHabit' : IDL.Func(
      [GoalId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'devReset' : IDL.Func([], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAnalytics' : IDL.Func([], [AnalyticsSummary], ['query']),
  'getCheckInsForGoal' : IDL.Func([GoalId], [IDL.Vec(CheckIn)], ['query']),
  'getCheckInsForGoalTimeline' : IDL.Func(
      [GoalId, IDL.Int],
      [IDL.Vec(CheckIn)],
      ['query'],
    ),
  'getCheckInsForPeriod' : IDL.Func(
      [GoalId, IDL.Int, IDL.Int],
      [IDL.Vec(CheckIn)],
      ['query'],
    ),
  'getHabit' : IDL.Func([GoalId], [IDL.Opt(HabitPublic)], ['query']),
  'getInteractionCount' : IDL.Func([CheckInId], [IDL.Nat], ['query']),
  'getMacroGoal' : IDL.Func([GoalId], [IDL.Opt(MacroGoalPublic)], ['query']),
  'getMyProfile' : IDL.Func([], [UserProfilePublic], ['query']),
  'getPartnerFeed' : IDL.Func([], [IDL.Vec(FeedItem)], ['query']),
  'getPartnerHabits' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : PartnerHabitDetail, 'err' : PartnerHabitError })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfilePublic)], ['query']),
  'listConnections' : IDL.Func([], [IDL.Vec(ConnectionPublic)], ['query']),
  'listHabitsByParent' : IDL.Func(
      [GoalId],
      [IDL.Variant({ 'ok' : IDL.Vec(HabitPublic), 'err' : IDL.Text })],
      ['query'],
    ),
  'listMyCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
  'listMyGoals' : IDL.Func([], [IDL.Vec(GoalWithHabitsPublic)], ['query']),
  'listMyObstacleTemplates' : IDL.Func(
      [],
      [IDL.Vec(ObstacleTemplate)],
      ['query'],
    ),
  'listMyReusableGoals' : IDL.Func(
      [],
      [IDL.Vec(ReusableGoalPublic)],
      ['query'],
    ),
  'listPartnerOverviews' : IDL.Func([], [IDL.Vec(PartnerOverview)], ['query']),
  'listPendingRequests' : IDL.Func([], [IDL.Vec(ConnectionPublic)], ['query']),
  'recordCheckIn' : IDL.Func([RecordCheckInRequest], [CheckIn], []),
  'recordInteraction' : IDL.Func(
      [CheckInId, InteractionType],
      [Interaction],
      [],
    ),
  'register' : IDL.Func([IDL.Text], [UserProfilePublic], []),
  'respondToConnection' : IDL.Func([ConnectionId, IDL.Bool], [IDL.Bool], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'sendConnectionRequest' : IDL.Func([UserId], [ConnectionPublic], []),
  'setTimezone' : IDL.Func([IDL.Text], [], []),
  'updateGoalState' : IDL.Func([GoalId, GoalState], [IDL.Bool], []),
  'updateHabit' : IDL.Func(
      [GoalId, UpdateHabitRequest],
      [IDL.Variant({ 'ok' : HabitPublic, 'err' : IDL.Text })],
      [],
    ),
  'updateMacroGoal' : IDL.Func(
      [GoalId, UpdateMacroGoalRequest],
      [IDL.Variant({ 'ok' : MacroGoalPublic, 'err' : IDL.Text })],
      [],
    ),
  'updateMyProfile' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        AvatarShape,
        AvatarColor,
        IDL.Opt(AvatarColorMode),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Int),
      ],
      [IDL.Variant({ 'ok' : UserProfilePublic, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GoalId = IDL.Nat;
  const ObstacleTemplateId = IDL.Nat;
  const CreateHabitRequest = IDL.Record({
    'startTime' : IDL.Opt(IDL.Text),
    'endTimeMinutes' : IDL.Opt(IDL.Nat),
    'endTime' : IDL.Opt(IDL.Text),
    'scheduledDays' : IDL.Opt(IDL.Vec(IDL.Text)),
    'startTimeMinutes' : IDL.Opt(IDL.Nat),
    'goalId' : GoalId,
    'themeColor' : IDL.Opt(IDL.Text),
    'wishDescription' : IDL.Opt(IDL.Text),
    'iconName' : IDL.Opt(IDL.Text),
    'ifThenPlan' : IDL.Text,
    'obstacleTemplateId' : IDL.Opt(ObstacleTemplateId),
    'isLockIn' : IDL.Bool,
    'lockInDurationMinutes' : IDL.Opt(IDL.Nat),
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const GoalState = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'paused' : IDL.Null,
  });
  const GoalCategory = IDL.Variant({
    'Productivity' : IDL.Null,
    'Learning' : IDL.Null,
    'Health' : IDL.Null,
    'Social' : IDL.Null,
    'Leisure' : IDL.Null,
  });
  const HabitPublic = IDL.Record({
    'id' : GoalId,
    'startTime' : IDL.Opt(IDL.Text),
    'endTimeMinutes' : IDL.Nat,
    'endTime' : IDL.Opt(IDL.Text),
    'scheduledDays' : IDL.Vec(IDL.Text),
    'owner' : UserId,
    'lastEditedAt' : IDL.Opt(Timestamp),
    'startTimeMinutes' : IDL.Nat,
    'createdAt' : Timestamp,
    'wish' : IDL.Text,
    'goalId' : GoalId,
    'themeColor' : IDL.Opt(IDL.Text),
    'wishDescription' : IDL.Text,
    'iconName' : IDL.Opt(IDL.Text),
    'ifThenPlan' : IDL.Text,
    'updatedAt' : Timestamp,
    'state' : GoalState,
    'obstacleTemplateId' : IDL.Opt(ObstacleTemplateId),
    'category' : GoalCategory,
    'isLockIn' : IDL.Bool,
    'outcome' : IDL.Text,
    'lockInDurationMinutes' : IDL.Nat,
  });
  const CreateMacroGoalRequest = IDL.Record({
    'wish' : IDL.Text,
    'themeColor' : IDL.Opt(IDL.Text),
    'wishDescription' : IDL.Text,
    'iconName' : IDL.Opt(IDL.Text),
    'category' : GoalCategory,
    'outcome' : IDL.Text,
  });
  const MacroGoalPublic = IDL.Record({
    'id' : GoalId,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'wish' : IDL.Text,
    'themeColor' : IDL.Opt(IDL.Text),
    'wishDescription' : IDL.Text,
    'iconName' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'state' : GoalState,
    'category' : GoalCategory,
    'outcome' : IDL.Text,
  });
  const CreateObstacleRequest = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const ObstacleTemplate = IDL.Record({
    'id' : ObstacleTemplateId,
    'title' : IDL.Text,
    'owner' : UserId,
    'description' : IDL.Text,
  });
  const CheckInId = IDL.Nat;
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const GoalAnalytics = IDL.Record({
    'totalMissed' : IDL.Nat,
    'completionRate' : IDL.Float64,
    'goalName' : IDL.Text,
    'goalId' : GoalId,
    'totalSkips' : IDL.Nat,
    'longestStreak' : IDL.Nat,
    'totalSuccesses' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const AnalyticsSummary = IDL.Record({
    'goals' : IDL.Vec(GoalAnalytics),
    'dailySuccessRate30Days' : IDL.Vec(IDL.Float64),
  });
  const CheckInType = IDL.Variant({
    'skip' : IDL.Null,
    'missedCheckIn' : IDL.Null,
    'missedCheckOut' : IDL.Null,
    'success' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const CheckIn = IDL.Record({
    'id' : CheckInId,
    'owner' : UserId,
    'goalId' : GoalId,
    'checkInType' : CheckInType,
    'obstacleTemplateId' : IDL.Opt(ObstacleTemplateId),
    'timestamp' : Timestamp,
    'executedIfThen' : IDL.Bool,
    'lockInStartedAt' : IDL.Opt(IDL.Int),
    'lockInEndedAt' : IDL.Opt(IDL.Int),
    'customObstacleNote' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const AvatarColor = IDL.Opt(IDL.Text);
  const AvatarColorMode = IDL.Variant({
    'Fill' : IDL.Null,
    'BorderOnly' : IDL.Null,
  });
  const AvatarShape = IDL.Opt(
    IDL.Variant({
      'Star' : IDL.Null,
      'Pentagon' : IDL.Null,
      'Triangle' : IDL.Null,
      'Hexagon' : IDL.Null,
      'Square' : IDL.Null,
    })
  );
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Opt(IDL.Text),
    'timezone' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'timezoneOffsetMinutes' : IDL.Int,
    'role' : UserRole,
    'email' : IDL.Opt(IDL.Text),
    'avatarColor' : AvatarColor,
    'avatarColorMode' : AvatarColorMode,
    'avatarShape' : AvatarShape,
  });
  const FeedItem = IDL.Record({
    'checkIn' : CheckIn,
    'goalName' : IDL.Text,
    'partnerDisplayName' : IDL.Text,
    'partnerAvatarColor' : AvatarColor,
    'highFiveCount' : IDL.Nat,
    'partnerAvatarColorMode' : AvatarColorMode,
    'partnerAvatarShape' : AvatarShape,
  });
  const PartnerHabitDetail = IDL.Record({
    'habits' : IDL.Vec(HabitPublic),
    'profile' : UserProfilePublic,
  });
  const PartnerHabitError = IDL.Variant({
    'notPartner' : IDL.Null,
    'profileNotFound' : IDL.Null,
  });
  const ConnectionId = IDL.Nat;
  const ConnectionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const ConnectionPublic = IDL.Record({
    'id' : ConnectionId,
    'status' : ConnectionStatus,
    'createdAt' : Timestamp,
    'toPrincipal' : UserId,
    'fromPrincipal' : UserId,
  });
  const GoalWithHabitsPublic = IDL.Record({
    'goal' : MacroGoalPublic,
    'habits' : IDL.Vec(HabitPublic),
  });
  const ReusableGoalPublic = IDL.Record({
    'id' : GoalId,
    'wish' : IDL.Text,
    'wishDescription' : IDL.Text,
    'state' : GoalState,
    'category' : GoalCategory,
  });
  const PartnerOverview = IDL.Record({
    'activeHabitCount' : IDL.Nat,
    'profile' : UserProfilePublic,
    'currentStreak' : IDL.Nat,
  });
  const RecordCheckInRequest = IDL.Record({
    'timezoneOffsetMinutes' : IDL.Int,
    'goalId' : GoalId,
    'checkInType' : CheckInType,
    'obstacleTemplateId' : IDL.Opt(ObstacleTemplateId),
    'executedIfThen' : IDL.Bool,
    'lockInStartedAt' : IDL.Opt(IDL.Int),
    'lockInEndedAt' : IDL.Opt(IDL.Int),
    'customObstacleNote' : IDL.Opt(IDL.Text),
  });
  const InteractionType = IDL.Variant({ 'highFive' : IDL.Null });
  const InteractionId = IDL.Nat;
  const Interaction = IDL.Record({
    'id' : InteractionId,
    'interactionType' : InteractionType,
    'fromPrincipal' : UserId,
    'checkInId' : CheckInId,
    'timestamp' : Timestamp,
  });
  const UpdateHabitRequest = IDL.Record({
    'startTime' : IDL.Opt(IDL.Text),
    'endTimeMinutes' : IDL.Opt(IDL.Nat),
    'endTime' : IDL.Opt(IDL.Text),
    'scheduledDays' : IDL.Opt(IDL.Vec(IDL.Text)),
    'timezoneOffsetMinutes' : IDL.Int,
    'startTimeMinutes' : IDL.Opt(IDL.Nat),
    'themeColor' : IDL.Opt(IDL.Text),
    'isTimeEdit' : IDL.Opt(IDL.Bool),
    'iconName' : IDL.Opt(IDL.Text),
    'ifThenPlan' : IDL.Opt(IDL.Text),
    'isLockIn' : IDL.Opt(IDL.Bool),
    'lockInDurationMinutes' : IDL.Opt(IDL.Nat),
  });
  const UpdateMacroGoalRequest = IDL.Record({
    'themeColor' : IDL.Opt(IDL.Text),
    'iconName' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'createHabit' : IDL.Func(
        [CreateHabitRequest],
        [IDL.Variant({ 'ok' : HabitPublic, 'err' : IDL.Text })],
        [],
      ),
    'createMacroGoal' : IDL.Func(
        [CreateMacroGoalRequest],
        [IDL.Variant({ 'ok' : MacroGoalPublic, 'err' : IDL.Text })],
        [],
      ),
    'createObstacleTemplate' : IDL.Func(
        [CreateObstacleRequest],
        [ObstacleTemplate],
        [],
      ),
    'deleteCheckIn' : IDL.Func(
        [CheckInId],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'err' : IDL.Variant({
              'sealed' : IDL.Text,
              'notFound' : IDL.Null,
              'unauthorized' : IDL.Null,
            }),
          }),
        ],
        [],
      ),
    'deleteGoal' : IDL.Func(
        [GoalId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteHabit' : IDL.Func(
        [GoalId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'devReset' : IDL.Func([], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAnalytics' : IDL.Func([], [AnalyticsSummary], ['query']),
    'getCheckInsForGoal' : IDL.Func([GoalId], [IDL.Vec(CheckIn)], ['query']),
    'getCheckInsForGoalTimeline' : IDL.Func(
        [GoalId, IDL.Int],
        [IDL.Vec(CheckIn)],
        ['query'],
      ),
    'getCheckInsForPeriod' : IDL.Func(
        [GoalId, IDL.Int, IDL.Int],
        [IDL.Vec(CheckIn)],
        ['query'],
      ),
    'getHabit' : IDL.Func([GoalId], [IDL.Opt(HabitPublic)], ['query']),
    'getInteractionCount' : IDL.Func([CheckInId], [IDL.Nat], ['query']),
    'getMacroGoal' : IDL.Func([GoalId], [IDL.Opt(MacroGoalPublic)], ['query']),
    'getMyProfile' : IDL.Func([], [UserProfilePublic], ['query']),
    'getPartnerFeed' : IDL.Func([], [IDL.Vec(FeedItem)], ['query']),
    'getPartnerHabits' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : PartnerHabitDetail, 'err' : PartnerHabitError })],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfilePublic)], ['query']),
    'listConnections' : IDL.Func([], [IDL.Vec(ConnectionPublic)], ['query']),
    'listHabitsByParent' : IDL.Func(
        [GoalId],
        [IDL.Variant({ 'ok' : IDL.Vec(HabitPublic), 'err' : IDL.Text })],
        ['query'],
      ),
    'listMyCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
    'listMyGoals' : IDL.Func([], [IDL.Vec(GoalWithHabitsPublic)], ['query']),
    'listMyObstacleTemplates' : IDL.Func(
        [],
        [IDL.Vec(ObstacleTemplate)],
        ['query'],
      ),
    'listMyReusableGoals' : IDL.Func(
        [],
        [IDL.Vec(ReusableGoalPublic)],
        ['query'],
      ),
    'listPartnerOverviews' : IDL.Func(
        [],
        [IDL.Vec(PartnerOverview)],
        ['query'],
      ),
    'listPendingRequests' : IDL.Func(
        [],
        [IDL.Vec(ConnectionPublic)],
        ['query'],
      ),
    'recordCheckIn' : IDL.Func([RecordCheckInRequest], [CheckIn], []),
    'recordInteraction' : IDL.Func(
        [CheckInId, InteractionType],
        [Interaction],
        [],
      ),
    'register' : IDL.Func([IDL.Text], [UserProfilePublic], []),
    'respondToConnection' : IDL.Func([ConnectionId, IDL.Bool], [IDL.Bool], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'sendConnectionRequest' : IDL.Func([UserId], [ConnectionPublic], []),
    'setTimezone' : IDL.Func([IDL.Text], [], []),
    'updateGoalState' : IDL.Func([GoalId, GoalState], [IDL.Bool], []),
    'updateHabit' : IDL.Func(
        [GoalId, UpdateHabitRequest],
        [IDL.Variant({ 'ok' : HabitPublic, 'err' : IDL.Text })],
        [],
      ),
    'updateMacroGoal' : IDL.Func(
        [GoalId, UpdateMacroGoalRequest],
        [IDL.Variant({ 'ok' : MacroGoalPublic, 'err' : IDL.Text })],
        [],
      ),
    'updateMyProfile' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          AvatarShape,
          AvatarColor,
          IDL.Opt(AvatarColorMode),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Int),
        ],
        [IDL.Variant({ 'ok' : UserProfilePublic, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };