/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSummary {
  'goals' : Array<GoalAnalytics>,
  'dailySuccessRate30Days' : Array<number>,
}
export interface CheckIn {
  'id' : CheckInId,
  'owner' : UserId,
  'goalId' : GoalId,
  'checkInType' : CheckInType,
  'obstacleTemplateId' : [] | [ObstacleTemplateId],
  'timestamp' : Timestamp,
  'executedIfThen' : boolean,
  'lockInStartedAt' : [] | [bigint],
  'lockInEndedAt' : [] | [bigint],
  'customObstacleNote' : [] | [string],
}
export type CheckInId = bigint;
export type CheckInType = { 'failedLockIn' : null } |
  { 'skip' : null } |
  { 'success' : null } |
  { 'inProgress' : null };
export type ConnectionId = bigint;
export interface ConnectionPublic {
  'id' : ConnectionId,
  'status' : ConnectionStatus,
  'createdAt' : Timestamp,
  'toPrincipal' : UserId,
  'fromPrincipal' : UserId,
}
export type ConnectionStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface CreateGoalRequest {
  'startTime' : [] | [string],
  'endTime' : [] | [string],
  'wish' : string,
  'themeColor' : [] | [string],
  'wishDescription' : string,
  'iconName' : [] | [string],
  'ifThenPlan' : string,
  'obstacleTemplateId' : [] | [ObstacleTemplateId],
  'isLockIn' : boolean,
  'outcome' : string,
}
export interface CreateObstacleRequest {
  'title' : string,
  'description' : string,
}
export interface FeedItem {
  'checkIn' : CheckIn,
  'goalName' : string,
  'partnerDisplayName' : string,
  'highFiveCount' : bigint,
}
export interface GoalAnalytics {
  'totalMissed' : bigint,
  'completionRate' : number,
  'goalName' : string,
  'goalId' : GoalId,
  'totalSkips' : bigint,
  'longestStreak' : bigint,
  'totalSuccesses' : bigint,
  'currentStreak' : bigint,
}
export type GoalId = bigint;
export interface GoalPublic {
  'id' : GoalId,
  'startTime' : [] | [string],
  'endTime' : [] | [string],
  'owner' : UserId,
  'createdAt' : Timestamp,
  'wish' : string,
  'themeColor' : [] | [string],
  'wishDescription' : string,
  'iconName' : [] | [string],
  'ifThenPlan' : string,
  'updatedAt' : Timestamp,
  'state' : GoalState,
  'obstacleTemplateId' : [] | [ObstacleTemplateId],
  'isLockIn' : boolean,
  'outcome' : string,
}
export type GoalState = { 'active' : null } |
  { 'completed' : null } |
  { 'abandoned' : null } |
  { 'paused' : null };
export interface Interaction {
  'id' : InteractionId,
  'interactionType' : InteractionType,
  'fromPrincipal' : UserId,
  'checkInId' : CheckInId,
  'timestamp' : Timestamp,
}
export type InteractionId = bigint;
export type InteractionType = { 'highFive' : null };
export interface ObstacleTemplate {
  'id' : ObstacleTemplateId,
  'title' : string,
  'owner' : UserId,
  'description' : string,
}
export type ObstacleTemplateId = bigint;
export interface RecordCheckInRequest {
  'goalId' : GoalId,
  'checkInType' : CheckInType,
  'obstacleTemplateId' : [] | [ObstacleTemplateId],
  'executedIfThen' : boolean,
  'lockInStartedAt' : [] | [bigint],
  'lockInEndedAt' : [] | [bigint],
  'customObstacleNote' : [] | [string],
}
export type Timestamp = bigint;
export interface UpdateGoalRequest {
  'startTime' : [] | [string],
  'endTime' : [] | [string],
  'wish' : [] | [string],
  'themeColor' : [] | [string],
  'wishDescription' : [] | [string],
  'iconName' : [] | [string],
  'ifThenPlan' : [] | [string],
  'isLockIn' : [] | [boolean],
}
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'timezone' : string,
  'username' : string,
  'displayName' : string,
  'role' : UserRole,
  'avatarEmoji' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null };
export interface _SERVICE {
  'createGoal' : ActorMethod<
    [CreateGoalRequest],
    { 'ok' : GoalPublic } |
      { 'err' : string }
  >,
  'createObstacleTemplate' : ActorMethod<
    [CreateObstacleRequest],
    ObstacleTemplate
  >,
  'deleteCheckIn' : ActorMethod<
    [CheckInId],
    { 'ok' : null } |
      { 'err' : { 'notFound' : null } | { 'unauthorized' : null } }
  >,
  'devReset' : ActorMethod<[], undefined>,
  'getAnalytics' : ActorMethod<[], AnalyticsSummary>,
  'getCheckInsForGoal' : ActorMethod<[GoalId], Array<CheckIn>>,
  'getCheckInsForGoalTimeline' : ActorMethod<[GoalId, bigint], Array<CheckIn>>,
  'getCheckInsForPeriod' : ActorMethod<
    [GoalId, bigint, bigint],
    Array<CheckIn>
  >,
  'getGoal' : ActorMethod<[GoalId], [] | [GoalPublic]>,
  'getInteractionCount' : ActorMethod<[CheckInId], bigint>,
  'getMyProfile' : ActorMethod<[], UserProfilePublic>,
  'getPartnerFeed' : ActorMethod<[], Array<FeedItem>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfilePublic]>,
  'isUsernameAvailable' : ActorMethod<[string], boolean>,
  'listAllUsers' : ActorMethod<[], Array<UserProfilePublic>>,
  'listConnections' : ActorMethod<[], Array<ConnectionPublic>>,
  'listMyCheckIns' : ActorMethod<[], Array<CheckIn>>,
  'listMyGoals' : ActorMethod<[], Array<GoalPublic>>,
  'listMyObstacleTemplates' : ActorMethod<[], Array<ObstacleTemplate>>,
  'listPendingRequests' : ActorMethod<[], Array<ConnectionPublic>>,
  'recordCheckIn' : ActorMethod<[RecordCheckInRequest], CheckIn>,
  'recordInteraction' : ActorMethod<[CheckInId, InteractionType], Interaction>,
  'register' : ActorMethod<[string], UserProfilePublic>,
  'respondToConnection' : ActorMethod<[ConnectionId, boolean], boolean>,
  'sendConnectionRequest' : ActorMethod<[UserId], ConnectionPublic>,
  'setTimezone' : ActorMethod<[string], undefined>,
  'updateGoal' : ActorMethod<
    [GoalId, UpdateGoalRequest],
    { 'ok' : GoalPublic } |
      { 'err' : string }
  >,
  'updateGoalState' : ActorMethod<[GoalId, GoalState], boolean>,
  'updateMyProfile' : ActorMethod<
    [[] | [string], [] | [string]],
    UserProfilePublic
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];