/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ObstacleTemplateId = IDL.Nat;
export const CreateGoalRequest = IDL.Record({
  'startTime' : IDL.Opt(IDL.Text),
  'endTime' : IDL.Opt(IDL.Text),
  'wish' : IDL.Text,
  'themeColor' : IDL.Opt(IDL.Text),
  'wishDescription' : IDL.Text,
  'iconName' : IDL.Opt(IDL.Text),
  'ifThenPlan' : IDL.Text,
  'obstacleTemplateId' : IDL.Opt(ObstacleTemplateId),
  'isLockIn' : IDL.Bool,
  'outcome' : IDL.Text,
});
export const GoalId = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const GoalState = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'abandoned' : IDL.Null,
  'paused' : IDL.Null,
});
export const GoalPublic = IDL.Record({
  'id' : GoalId,
  'startTime' : IDL.Opt(IDL.Text),
  'endTime' : IDL.Opt(IDL.Text),
  'owner' : UserId,
  'createdAt' : Timestamp,
  'wish' : IDL.Text,
  'themeColor' : IDL.Opt(IDL.Text),
  'wishDescription' : IDL.Text,
  'iconName' : IDL.Opt(IDL.Text),
  'ifThenPlan' : IDL.Text,
  'updatedAt' : Timestamp,
  'state' : GoalState,
  'obstacleTemplateId' : IDL.Opt(ObstacleTemplateId),
  'isLockIn' : IDL.Bool,
  'outcome' : IDL.Text,
});
export const CreateObstacleRequest = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const ObstacleTemplate = IDL.Record({
  'id' : ObstacleTemplateId,
  'title' : IDL.Text,
  'owner' : UserId,
  'description' : IDL.Text,
});
export const CheckInId = IDL.Nat;
export const GoalAnalytics = IDL.Record({
  'totalMissed' : IDL.Nat,
  'completionRate' : IDL.Float64,
  'goalName' : IDL.Text,
  'goalId' : GoalId,
  'totalSkips' : IDL.Nat,
  'longestStreak' : IDL.Nat,
  'totalSuccesses' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const AnalyticsSummary = IDL.Record({
  'goals' : IDL.Vec(GoalAnalytics),
  'dailySuccessRate30Days' : IDL.Vec(IDL.Float64),
});
export const CheckInType = IDL.Variant({
  'skip' : IDL.Null,
  'missedCheckIn' : IDL.Null,
  'missedCheckOut' : IDL.Null,
  'success' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const CheckIn = IDL.Record({
  'id' : CheckInId,
  'owner' : UserId,
  'goalId' : GoalId,
  'checkInType' : CheckInType,
  'obstacleTemplateId' : IDL.Opt(ObstacleTemplateId),
  'timestamp' : Timestamp,
  'executedIfThen' : IDL.Bool,
  'lockInStartedAt' : IDL.Opt(IDL.Int),
  'lockInEndedAt' : IDL.Opt(IDL.Int),
  'customObstacleNote' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Opt(IDL.Text),
  'timezone' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'role' : UserRole,
  'avatarEmoji' : IDL.Text,
});
export const FeedItem = IDL.Record({
  'checkIn' : CheckIn,
  'goalName' : IDL.Text,
  'partnerDisplayName' : IDL.Text,
  'highFiveCount' : IDL.Nat,
});
export const ConnectionId = IDL.Nat;
export const ConnectionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const ConnectionPublic = IDL.Record({
  'id' : ConnectionId,
  'status' : ConnectionStatus,
  'createdAt' : Timestamp,
  'toPrincipal' : UserId,
  'fromPrincipal' : UserId,
});
export const RecordCheckInRequest = IDL.Record({
  'timezoneOffsetMinutes' : IDL.Int,
  'goalId' : GoalId,
  'checkInType' : CheckInType,
  'obstacleTemplateId' : IDL.Opt(ObstacleTemplateId),
  'executedIfThen' : IDL.Bool,
  'lockInStartedAt' : IDL.Opt(IDL.Int),
  'lockInEndedAt' : IDL.Opt(IDL.Int),
  'customObstacleNote' : IDL.Opt(IDL.Text),
});
export const InteractionType = IDL.Variant({ 'highFive' : IDL.Null });
export const InteractionId = IDL.Nat;
export const Interaction = IDL.Record({
  'id' : InteractionId,
  'interactionType' : InteractionType,
  'fromPrincipal' : UserId,
  'checkInId' : CheckInId,
  'timestamp' : Timestamp,
});
export const UpdateGoalRequest = IDL.Record({
  'startTime' : IDL.Opt(IDL.Text),
  'endTime' : IDL.Opt(IDL.Text),
  'wish' : IDL.Opt(IDL.Text),
  'themeColor' : IDL.Opt(IDL.Text),
  'wishDescription' : IDL.Opt(IDL.Text),
  'iconName' : IDL.Opt(IDL.Text),
  'ifThenPlan' : IDL.Opt(IDL.Text),
  'isLockIn' : IDL.Opt(IDL.Bool),
});

export const idlService = IDL.Service({
  'createGoal' : IDL.Func(
      [CreateGoalRequest],
      [IDL.Variant({ 'ok' : GoalPublic, 'err' : IDL.Text })],
      [],
    ),
  'createObstacleTemplate' : IDL.Func(
      [CreateObstacleRequest],
      [ObstacleTemplate],
      [],
    ),
  'deleteCheckIn' : IDL.Func(
      [CheckInId],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'err' : IDL.Variant({
            'sealed' : IDL.Text,
            'notFound' : IDL.Null,
            'unauthorized' : IDL.Null,
          }),
        }),
      ],
      [],
    ),
  'devReset' : IDL.Func([], [], []),
  'getAnalytics' : IDL.Func([], [AnalyticsSummary], ['query']),
  'getCheckInsForGoal' : IDL.Func([GoalId], [IDL.Vec(CheckIn)], ['query']),
  'getCheckInsForGoalTimeline' : IDL.Func(
      [GoalId, IDL.Int],
      [IDL.Vec(CheckIn)],
      ['query'],
    ),
  'getCheckInsForPeriod' : IDL.Func(
      [GoalId, IDL.Int, IDL.Int],
      [IDL.Vec(CheckIn)],
      ['query'],
    ),
  'getGoal' : IDL.Func([GoalId], [IDL.Opt(GoalPublic)], ['query']),
  'getInteractionCount' : IDL.Func([CheckInId], [IDL.Nat], ['query']),
  'getMyProfile' : IDL.Func([], [UserProfilePublic], ['query']),
  'getPartnerFeed' : IDL.Func([], [IDL.Vec(FeedItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfilePublic)], ['query']),
  'listConnections' : IDL.Func([], [IDL.Vec(ConnectionPublic)], ['query']),
  'listMyCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
  'listMyGoals' : IDL.Func([], [IDL.Vec(GoalPublic)], ['query']),
  'listMyObstacleTemplates' : IDL.Func(
      [],
      [IDL.Vec(ObstacleTemplate)],
      ['query'],
    ),
  'listPendingRequests' : IDL.Func([], [IDL.Vec(ConnectionPublic)], ['query']),
  'recordCheckIn' : IDL.Func([RecordCheckInRequest], [CheckIn], []),
  'recordInteraction' : IDL.Func(
      [CheckInId, InteractionType],
      [Interaction],
      [],
    ),
  'register' : IDL.Func([IDL.Text], [UserProfilePublic], []),
  'respondToConnection' : IDL.Func([ConnectionId, IDL.Bool], [IDL.Bool], []),
  'sendConnectionRequest' : IDL.Func([UserId], [ConnectionPublic], []),
  'setTimezone' : IDL.Func([IDL.Text], [], []),
  'updateGoal' : IDL.Func(
      [GoalId, UpdateGoalRequest],
      [IDL.Variant({ 'ok' : GoalPublic, 'err' : IDL.Text })],
      [],
    ),
  'updateGoalState' : IDL.Func([GoalId, GoalState], [IDL.Bool], []),
  'updateMyProfile' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : UserProfilePublic, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ObstacleTemplateId = IDL.Nat;
  const CreateGoalRequest = IDL.Record({
    'startTime' : IDL.Opt(IDL.Text),
    'endTime' : IDL.Opt(IDL.Text),
    'wish' : IDL.Text,
    'themeColor' : IDL.Opt(IDL.Text),
    'wishDescription' : IDL.Text,
    'iconName' : IDL.Opt(IDL.Text),
    'ifThenPlan' : IDL.Text,
    'obstacleTemplateId' : IDL.Opt(ObstacleTemplateId),
    'isLockIn' : IDL.Bool,
    'outcome' : IDL.Text,
  });
  const GoalId = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const GoalState = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'abandoned' : IDL.Null,
    'paused' : IDL.Null,
  });
  const GoalPublic = IDL.Record({
    'id' : GoalId,
    'startTime' : IDL.Opt(IDL.Text),
    'endTime' : IDL.Opt(IDL.Text),
    'owner' : UserId,
    'createdAt' : Timestamp,
    'wish' : IDL.Text,
    'themeColor' : IDL.Opt(IDL.Text),
    'wishDescription' : IDL.Text,
    'iconName' : IDL.Opt(IDL.Text),
    'ifThenPlan' : IDL.Text,
    'updatedAt' : Timestamp,
    'state' : GoalState,
    'obstacleTemplateId' : IDL.Opt(ObstacleTemplateId),
    'isLockIn' : IDL.Bool,
    'outcome' : IDL.Text,
  });
  const CreateObstacleRequest = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const ObstacleTemplate = IDL.Record({
    'id' : ObstacleTemplateId,
    'title' : IDL.Text,
    'owner' : UserId,
    'description' : IDL.Text,
  });
  const CheckInId = IDL.Nat;
  const GoalAnalytics = IDL.Record({
    'totalMissed' : IDL.Nat,
    'completionRate' : IDL.Float64,
    'goalName' : IDL.Text,
    'goalId' : GoalId,
    'totalSkips' : IDL.Nat,
    'longestStreak' : IDL.Nat,
    'totalSuccesses' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const AnalyticsSummary = IDL.Record({
    'goals' : IDL.Vec(GoalAnalytics),
    'dailySuccessRate30Days' : IDL.Vec(IDL.Float64),
  });
  const CheckInType = IDL.Variant({
    'skip' : IDL.Null,
    'missedCheckIn' : IDL.Null,
    'missedCheckOut' : IDL.Null,
    'success' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const CheckIn = IDL.Record({
    'id' : CheckInId,
    'owner' : UserId,
    'goalId' : GoalId,
    'checkInType' : CheckInType,
    'obstacleTemplateId' : IDL.Opt(ObstacleTemplateId),
    'timestamp' : Timestamp,
    'executedIfThen' : IDL.Bool,
    'lockInStartedAt' : IDL.Opt(IDL.Int),
    'lockInEndedAt' : IDL.Opt(IDL.Int),
    'customObstacleNote' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Opt(IDL.Text),
    'timezone' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'role' : UserRole,
    'avatarEmoji' : IDL.Text,
  });
  const FeedItem = IDL.Record({
    'checkIn' : CheckIn,
    'goalName' : IDL.Text,
    'partnerDisplayName' : IDL.Text,
    'highFiveCount' : IDL.Nat,
  });
  const ConnectionId = IDL.Nat;
  const ConnectionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const ConnectionPublic = IDL.Record({
    'id' : ConnectionId,
    'status' : ConnectionStatus,
    'createdAt' : Timestamp,
    'toPrincipal' : UserId,
    'fromPrincipal' : UserId,
  });
  const RecordCheckInRequest = IDL.Record({
    'timezoneOffsetMinutes' : IDL.Int,
    'goalId' : GoalId,
    'checkInType' : CheckInType,
    'obstacleTemplateId' : IDL.Opt(ObstacleTemplateId),
    'executedIfThen' : IDL.Bool,
    'lockInStartedAt' : IDL.Opt(IDL.Int),
    'lockInEndedAt' : IDL.Opt(IDL.Int),
    'customObstacleNote' : IDL.Opt(IDL.Text),
  });
  const InteractionType = IDL.Variant({ 'highFive' : IDL.Null });
  const InteractionId = IDL.Nat;
  const Interaction = IDL.Record({
    'id' : InteractionId,
    'interactionType' : InteractionType,
    'fromPrincipal' : UserId,
    'checkInId' : CheckInId,
    'timestamp' : Timestamp,
  });
  const UpdateGoalRequest = IDL.Record({
    'startTime' : IDL.Opt(IDL.Text),
    'endTime' : IDL.Opt(IDL.Text),
    'wish' : IDL.Opt(IDL.Text),
    'themeColor' : IDL.Opt(IDL.Text),
    'wishDescription' : IDL.Opt(IDL.Text),
    'iconName' : IDL.Opt(IDL.Text),
    'ifThenPlan' : IDL.Opt(IDL.Text),
    'isLockIn' : IDL.Opt(IDL.Bool),
  });
  
  return IDL.Service({
    'createGoal' : IDL.Func(
        [CreateGoalRequest],
        [IDL.Variant({ 'ok' : GoalPublic, 'err' : IDL.Text })],
        [],
      ),
    'createObstacleTemplate' : IDL.Func(
        [CreateObstacleRequest],
        [ObstacleTemplate],
        [],
      ),
    'deleteCheckIn' : IDL.Func(
        [CheckInId],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'err' : IDL.Variant({
              'sealed' : IDL.Text,
              'notFound' : IDL.Null,
              'unauthorized' : IDL.Null,
            }),
          }),
        ],
        [],
      ),
    'devReset' : IDL.Func([], [], []),
    'getAnalytics' : IDL.Func([], [AnalyticsSummary], ['query']),
    'getCheckInsForGoal' : IDL.Func([GoalId], [IDL.Vec(CheckIn)], ['query']),
    'getCheckInsForGoalTimeline' : IDL.Func(
        [GoalId, IDL.Int],
        [IDL.Vec(CheckIn)],
        ['query'],
      ),
    'getCheckInsForPeriod' : IDL.Func(
        [GoalId, IDL.Int, IDL.Int],
        [IDL.Vec(CheckIn)],
        ['query'],
      ),
    'getGoal' : IDL.Func([GoalId], [IDL.Opt(GoalPublic)], ['query']),
    'getInteractionCount' : IDL.Func([CheckInId], [IDL.Nat], ['query']),
    'getMyProfile' : IDL.Func([], [UserProfilePublic], ['query']),
    'getPartnerFeed' : IDL.Func([], [IDL.Vec(FeedItem)], ['query']),
    'getUserProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfilePublic)], ['query']),
    'listConnections' : IDL.Func([], [IDL.Vec(ConnectionPublic)], ['query']),
    'listMyCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
    'listMyGoals' : IDL.Func([], [IDL.Vec(GoalPublic)], ['query']),
    'listMyObstacleTemplates' : IDL.Func(
        [],
        [IDL.Vec(ObstacleTemplate)],
        ['query'],
      ),
    'listPendingRequests' : IDL.Func(
        [],
        [IDL.Vec(ConnectionPublic)],
        ['query'],
      ),
    'recordCheckIn' : IDL.Func([RecordCheckInRequest], [CheckIn], []),
    'recordInteraction' : IDL.Func(
        [CheckInId, InteractionType],
        [Interaction],
        [],
      ),
    'register' : IDL.Func([IDL.Text], [UserProfilePublic], []),
    'respondToConnection' : IDL.Func([ConnectionId, IDL.Bool], [IDL.Bool], []),
    'sendConnectionRequest' : IDL.Func([UserId], [ConnectionPublic], []),
    'setTimezone' : IDL.Func([IDL.Text], [], []),
    'updateGoal' : IDL.Func(
        [GoalId, UpdateGoalRequest],
        [IDL.Variant({ 'ok' : GoalPublic, 'err' : IDL.Text })],
        [],
      ),
    'updateGoalState' : IDL.Func([GoalId, GoalState], [IDL.Bool], []),
    'updateMyProfile' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : UserProfilePublic, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };