/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSummary {
  'categoryBreakdown' : Array<CategoryStat>,
  'dayOfWeek' : Array<DayOfWeekStat>,
  'bestDayOfWeek' : [] | [bigint],
  'overallIfThenEffectiveness' : IfThenEffectiveness,
  'habits' : Array<HabitAnalytics>,
  'worstDayOfWeek' : [] | [bigint],
}
export type AvatarColor = [] | [string];
export type AvatarColorMode = { 'Fill' : null } |
  { 'BorderOnly' : null };
export type AvatarShape = [] | [
  { 'Star' : null } |
    { 'Pentagon' : null } |
    { 'Triangle' : null } |
    { 'Hexagon' : null } |
    { 'Square' : null }
];
export interface CategoryStat {
  'successes' : bigint,
  'total' : bigint,
  'rate' : number,
  'category' : GoalCategory,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface CheckIn {
  'id' : CheckInId,
  'owner' : UserId,
  'note' : [] | [string],
  'goalId' : GoalId,
  'checkInType' : CheckInType,
  'obstacleTemplateId' : [] | [ObstacleTemplateId],
  'timestamp' : Timestamp,
  'executedIfThen' : boolean,
  'lockInStartedAt' : [] | [bigint],
  'lockInEndedAt' : [] | [bigint],
}
export type CheckInId = bigint;
export type CheckInType = { 'skip' : null } |
  { 'missedCheckIn' : null } |
  { 'missedCheckOut' : null } |
  { 'success' : null } |
  { 'inProgress' : null };
export type ConnectionId = bigint;
export interface ConnectionPublic {
  'id' : ConnectionId,
  'status' : ConnectionStatus,
  'createdAt' : Timestamp,
  'toPrincipal' : UserId,
  'fromPrincipal' : UserId,
}
export type ConnectionStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface CreateHabitRequest {
  'startTime' : [] | [string],
  'endTimeMinutes' : [] | [bigint],
  'endTime' : [] | [string],
  'scheduledDays' : [] | [Array<string>],
  'startTimeMinutes' : [] | [bigint],
  'goalId' : GoalId,
  'themeColor' : [] | [string],
  'wishDescription' : [] | [string],
  'iconName' : [] | [string],
  'ifThenPlan' : string,
  'obstacleTemplateId' : [] | [ObstacleTemplateId],
  'isLockIn' : boolean,
  'lockInDurationMinutes' : [] | [bigint],
}
export interface CreateMacroGoalRequest {
  'wish' : string,
  'wishDescription' : string,
  'iconName' : [] | [string],
  'category' : GoalCategory,
  'outcome' : string,
}
export interface DayOfWeekStat {
  'successes' : bigint,
  'total' : bigint,
  'dayOfWeek' : bigint,
  'rate' : number,
  'dayName' : string,
}
export interface FeedItem {
  'checkIn' : CheckIn,
  'goalName' : string,
  'partnerDisplayName' : string,
  'partnerAvatarColor' : AvatarColor,
  'highFiveCount' : bigint,
  'partnerAvatarColorMode' : AvatarColorMode,
  'partnerAvatarShape' : AvatarShape,
}
export interface FollowThroughRate {
  'successes' : bigint,
  'total' : bigint,
  'rate' : number,
}
export type GoalCategory = { 'Productivity' : null } |
  { 'Learning' : null } |
  { 'Health' : null } |
  { 'Social' : null } |
  { 'Leisure' : null };
export type GoalId = bigint;
export type GoalState = { 'active' : null } |
  { 'completed' : null } |
  { 'paused' : null };
export interface GoalWithHabitsPublic {
  'goal' : MacroGoalPublic,
  'habits' : Array<HabitPublic>,
}
export interface HabitAnalytics {
  'ifThenEffectiveness' : IfThenEffectiveness,
  'predictedObstacle' : [] | [ObstacleStat],
  'habitName' : string,
  'habitId' : GoalId,
  'actualObstacles' : Array<ObstacleStat>,
  'shownUpDays' : bigint,
  'category' : GoalCategory,
}
export interface HabitPublic {
  'id' : GoalId,
  'startTime' : [] | [string],
  'endTimeMinutes' : bigint,
  'endTime' : [] | [string],
  'scheduledDays' : Array<string>,
  'owner' : UserId,
  'lastEditedAt' : [] | [Timestamp],
  'startTimeMinutes' : bigint,
  'createdAt' : Timestamp,
  'wish' : string,
  'goalId' : GoalId,
  'themeColor' : [] | [string],
  'wishDescription' : string,
  'ifThenPlan' : string,
  'updatedAt' : Timestamp,
  'state' : GoalState,
  'obstacleTemplateId' : [] | [ObstacleTemplateId],
  'category' : GoalCategory,
  'isLockIn' : boolean,
  'outcome' : string,
  'lockInDurationMinutes' : bigint,
}
export interface IfThenEffectiveness {
  'notUsedPlan' : FollowThroughRate,
  'usedPlan' : FollowThroughRate,
}
export interface Interaction {
  'id' : InteractionId,
  'interactionType' : InteractionType,
  'fromPrincipal' : UserId,
  'checkInId' : CheckInId,
  'timestamp' : Timestamp,
}
export type InteractionId = bigint;
export type InteractionType = { 'highFive' : null };
export interface MacroGoalPublic {
  'id' : GoalId,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'wish' : string,
  'wishDescription' : string,
  'iconName' : [] | [string],
  'updatedAt' : Timestamp,
  'state' : GoalState,
  'category' : GoalCategory,
  'outcome' : string,
}
export interface ObstacleStat {
  'obstacleName' : string,
  'count' : bigint,
  'obstacleTemplateId' : [] | [ObstacleTemplateId],
}
export interface ObstacleTemplate {
  'id' : ObstacleTemplateId,
  'title' : string,
  'owner' : UserId,
  'description' : string,
}
export type ObstacleTemplateId = bigint;
export interface PartnerHabitDetail {
  'habits' : Array<HabitPublic>,
  'profile' : UserProfilePublic,
}
export type PartnerHabitError = { 'notPartner' : null } |
  { 'profileNotFound' : null };
export interface PartnerOverview {
  'activeHabitCount' : bigint,
  'profile' : UserProfilePublic,
  'currentStreak' : bigint,
}
export interface RecordCheckInRequest {
  'timezoneOffsetMinutes' : bigint,
  'note' : [] | [string],
  'goalId' : GoalId,
  'checkInType' : CheckInType,
  'obstacleTemplateId' : [] | [ObstacleTemplateId],
  'executedIfThen' : boolean,
  'lockInStartedAt' : [] | [bigint],
  'lockInEndedAt' : [] | [bigint],
}
export interface ResolveObstacleRequest { 'labelText' : string }
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface ReusableGoalPublic {
  'id' : GoalId,
  'wish' : string,
  'wishDescription' : string,
  'state' : GoalState,
  'category' : GoalCategory,
}
export type Timestamp = bigint;
export interface UpdateHabitRequest {
  'startTime' : [] | [string],
  'endTimeMinutes' : [] | [bigint],
  'endTime' : [] | [string],
  'scheduledDays' : [] | [Array<string>],
  'timezoneOffsetMinutes' : bigint,
  'startTimeMinutes' : [] | [bigint],
  'themeColor' : [] | [string],
  'isTimeEdit' : [] | [boolean],
  'iconName' : [] | [string],
  'ifThenPlan' : [] | [string],
  'obstacleTemplateId' : [] | [ObstacleTemplateId],
  'isLockIn' : [] | [boolean],
  'lockInDurationMinutes' : [] | [bigint],
}
export interface UpdateMacroGoalRequest { 'iconName' : [] | [string] }
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'bio' : [] | [string],
  'timezone' : string,
  'username' : string,
  'displayName' : string,
  'timezoneOffsetMinutes' : bigint,
  'role' : UserRole,
  'email' : [] | [string],
  'avatarColor' : AvatarColor,
  'avatarColorMode' : AvatarColorMode,
  'avatarShape' : AvatarShape,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  /**
   * / Create a habit inside an existing macro goal. `request.goalId` is
   * / REQUIRED — the habit must reference an existing macro goal owned by the
   * / caller. The habit inherits the parent's category; wish/outcome are
   * / sourced from the parent and read-only. The habit's wishDescription
   * / (displayed name) defaults to the parent's, but is overridden by
   * / `request.wishDescription` when the caller supplies one.
   */
  'createHabit' : ActorMethod<
    [CreateHabitRequest],
    { 'ok' : HabitPublic } |
      { 'err' : string }
  >,
  /**
   * / Create a macro goal (a container). Captured by the goal wizard:
   * / category, wish, outcome (wishDescription). Does NOT accept Lock-In or
   * / schedule fields.
   */
  'createMacroGoal' : ActorMethod<
    [CreateMacroGoalRequest],
    { 'ok' : MacroGoalPublic } |
      { 'err' : string }
  >,
  'deleteCheckIn' : ActorMethod<
    [CheckInId],
    { 'ok' : null } |
      {
        'err' : { 'sealed' : string } |
          { 'notFound' : null } |
          { 'unauthorized' : null }
      }
  >,
  /**
   * / Permanently delete a macro goal and all of its child habits in a single
   * / atomic operation. Removes every child habit's check-ins, timeline
   * / entries, and feed interactions before removing the habits and the goal
   * / itself. All-or-nothing: partial failure cannot leave dangling habits.
   * / Hard-delete is final — no soft-delete or recoverable state.
   */
  'deleteGoal' : ActorMethod<[GoalId], { 'ok' : null } | { 'err' : string }>,
  /**
   * / Permanently delete a single habit in one atomic operation. Removes the
   * / habit's check-ins, timeline entries, and feed interactions before
   * / removing the habit itself. All-or-nothing: partial failure cannot leave
   * / dangling check-ins. Hard-delete is final — no soft-delete or recoverable
   * / state. Scoped to one habit — does not touch the parent macro goal or
   * / sibling habits.
   */
  'deleteHabit' : ActorMethod<[GoalId], { 'ok' : null } | { 'err' : string }>,
  'devReset' : ActorMethod<[], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getAnalytics' : ActorMethod<[bigint], AnalyticsSummary>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCheckInsForGoal' : ActorMethod<[GoalId], Array<CheckIn>>,
  'getCheckInsForGoalTimeline' : ActorMethod<[GoalId, bigint], Array<CheckIn>>,
  'getCheckInsForPeriod' : ActorMethod<
    [GoalId, bigint, bigint],
    Array<CheckIn>
  >,
  /**
   * / Retrieve a habit by ID. Only the owning caller can see it.
   */
  'getHabit' : ActorMethod<[GoalId], [] | [HabitPublic]>,
  'getInteractionCount' : ActorMethod<[CheckInId], bigint>,
  /**
   * / Retrieve a macro goal by ID. Only the owning caller can see it.
   */
  'getMacroGoal' : ActorMethod<[GoalId], [] | [MacroGoalPublic]>,
  'getMyProfile' : ActorMethod<[], UserProfilePublic>,
  'getPartnerFeed' : ActorMethod<[], Array<FeedItem>>,
  /**
   * / Returns the full habit detail for a single partner. Returns #notPartner
   * / for any non-partner, pending-only, or unconnected caller — no habit data
   * / leaks.
   */
  'getPartnerHabits' : ActorMethod<
    [Principal],
    { 'ok' : PartnerHabitDetail } |
      { 'err' : PartnerHabitError }
  >,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfilePublic]>,
  'isUsernameAvailable' : ActorMethod<[string], boolean>,
  'listAllUsers' : ActorMethod<[], Array<UserProfilePublic>>,
  'listConnections' : ActorMethod<[], Array<ConnectionPublic>>,
  /**
   * / List habits linked to a specific macro goal (by parent goalId).
   */
  'listHabitsByParent' : ActorMethod<
    [GoalId],
    { 'ok' : Array<HabitPublic> } |
      { 'err' : string }
  >,
  'listMyCheckIns' : ActorMethod<[], Array<CheckIn>>,
  /**
   * / List the caller's macro goals, each grouped with its linked habits.
   * / Supports the dashboard grouping requirement.
   */
  'listMyGoals' : ActorMethod<[], Array<GoalWithHabitsPublic>>,
  /**
   * / Returns the caller's reusable macro goals for the wizard chips.
   * / Each entry exposes id, wish, wishDescription, state, and category.
   */
  'listMyReusableGoals' : ActorMethod<[], Array<ReusableGoalPublic>>,
  /**
   * / Returns an overview row for every accepted, mutual partner of the
   * / caller. Each row has the partner's profile, active habit count, and
   * / current streak. Pending requests and non-partners are never included.
   */
  'listPartnerOverviews' : ActorMethod<[], Array<PartnerOverview>>,
  'listPendingRequests' : ActorMethod<[], Array<ConnectionPublic>>,
  'markCheckInIfThenUsed' : ActorMethod<
    [CheckInId],
    { 'ok' : null } |
      { 'err' : { 'notFound' : null } | { 'unauthorized' : null } }
  >,
  'recordCheckIn' : ActorMethod<[RecordCheckInRequest], CheckIn>,
  'recordInteraction' : ActorMethod<[CheckInId, InteractionType], Interaction>,
  'register' : ActorMethod<[string], UserProfilePublic>,
  /**
   * / Resolves a built-in obstacle label to one of the seven fixed built-in
   * / obstacles. The match is case-insensitive on the built-in title. If the
   * / label is not one of the seven built-ins, the call traps — a custom
   * / obstacle can never be created. Returns the matching built-in
   * / `ObstacleTemplate` with its stable id.
   */
  'resolveObstacleLabel' : ActorMethod<
    [ResolveObstacleRequest],
    ObstacleTemplate
  >,
  'respondToConnection' : ActorMethod<[ConnectionId, boolean], boolean>,
  'schema' : ActorMethod<[], string>,
  'sendConnectionRequest' : ActorMethod<[UserId], ConnectionPublic>,
  'setTimezone' : ActorMethod<[string], undefined>,
  /**
   * / Transition a goal (macro or habit) to a new state.
   */
  'updateGoalState' : ActorMethod<[GoalId, GoalState], boolean>,
  /**
   * / Update an editable habit. wish/wishDescription/outcome/category are
   * / immutable (sourced from the parent macro goal).
   */
  'updateHabit' : ActorMethod<
    [GoalId, UpdateHabitRequest],
    { 'ok' : HabitPublic } |
      { 'err' : string }
  >,
  /**
   * / Update an editable macro goal. Only cosmetic fields are editable;
   * / wish/wishDescription/outcome/category are immutable after creation.
   */
  'updateMacroGoal' : ActorMethod<
    [GoalId, UpdateMacroGoalRequest],
    { 'ok' : MacroGoalPublic } |
      { 'err' : string }
  >,
  'updateMyProfile' : ActorMethod<
    [
      [] | [string],
      AvatarShape,
      AvatarColor,
      [] | [AvatarColorMode],
      [] | [string],
      [] | [string],
      [] | [bigint],
    ],
    { 'ok' : UserProfilePublic } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];