/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UpdateGoalRequest {
    startTime?: string;
    emailNotifications?: boolean;
    endTime?: string;
    timezoneOffsetMinutes: bigint;
    wish?: string;
    themeColor?: string;
    wishDescription?: string;
    iconName?: string;
    ifThenPlan?: string;
    isLockIn?: boolean;
    reminderOffset?: bigint;
    intentTime?: string;
    outcome?: string;
}
export type Timestamp = bigint;
export interface RecordCheckInRequest {
    timezoneOffsetMinutes: bigint;
    goalId: GoalId;
    checkInType: CheckInType;
    obstacleTemplateId?: ObstacleTemplateId;
    executedIfThen: boolean;
    lockInStartedAt?: bigint;
    lockInEndedAt?: bigint;
    customObstacleNote?: string;
}
export interface GoalAnalytics {
    totalMissed: bigint;
    completionRate: number;
    goalName: string;
    goalId: GoalId;
    totalSkips: bigint;
    longestStreak: bigint;
    totalSuccesses: bigint;
    currentStreak: bigint;
}
export interface CreateGoalRequest {
    startTime?: string;
    endTime?: string;
    wish: string;
    themeColor?: string;
    wishDescription: string;
    iconName?: string;
    ifThenPlan: string;
    obstacleTemplateId?: ObstacleTemplateId;
    isLockIn: boolean;
    outcome: string;
}
export type ObstacleTemplateId = bigint;
export type ConnectionId = bigint;
export interface AnalyticsSummary {
    goals: Array<GoalAnalytics>;
    dailySuccessRate30Days: Array<number>;
}
export interface GoalPublic {
    id: GoalId;
    startTime?: string;
    emailNotifications: boolean;
    endTime?: string;
    owner: UserId;
    lastEditedAt?: Timestamp;
    createdAt: Timestamp;
    wish: string;
    themeColor?: string;
    wishDescription: string;
    iconName?: string;
    ifThenPlan: string;
    updatedAt: Timestamp;
    state: GoalState;
    obstacleTemplateId?: ObstacleTemplateId;
    isLockIn: boolean;
    reminderOffset?: bigint;
    intentTime?: string;
    outcome: string;
}
export interface UserProfilePublic {
    id: UserId;
    bio?: string;
    timezone: string;
    username: string;
    displayName: string;
    role: UserRole;
    email?: string;
    avatarEmoji: string;
}
export interface CreateObstacleRequest {
    title: string;
    description: string;
}
export type UserId = Principal;
export interface ObstacleTemplate {
    id: ObstacleTemplateId;
    title: string;
    owner: UserId;
    description: string;
}
export type InteractionId = bigint;
export interface CheckIn {
    id: CheckInId;
    owner: UserId;
    goalId: GoalId;
    checkInType: CheckInType;
    obstacleTemplateId?: ObstacleTemplateId;
    timestamp: Timestamp;
    executedIfThen: boolean;
    lockInStartedAt?: bigint;
    lockInEndedAt?: bigint;
    customObstacleNote?: string;
}
export interface FeedItem {
    checkIn: CheckIn;
    goalName: string;
    partnerDisplayName: string;
    highFiveCount: bigint;
}
export interface ConnectionPublic {
    id: ConnectionId;
    status: ConnectionStatus;
    createdAt: Timestamp;
    toPrincipal: UserId;
    fromPrincipal: UserId;
}
export type CheckInId = bigint;
export interface Interaction {
    id: InteractionId;
    interactionType: InteractionType;
    fromPrincipal: UserId;
    checkInId: CheckInId;
    timestamp: Timestamp;
}
export type GoalId = bigint;
export enum CheckInType {
    skip = "skip",
    missedCheckIn = "missedCheckIn",
    missedCheckOut = "missedCheckOut",
    success = "success",
    inProgress = "inProgress"
}
export enum ConnectionStatus {
    pending = "pending",
    rejected = "rejected",
    accepted = "accepted"
}
export enum GoalState {
    active = "active",
    completed = "completed",
    abandoned = "abandoned",
    paused = "paused"
}
export enum InteractionType {
    highFive = "highFive"
}
export enum UserRole {
    admin = "admin",
    user = "user"
}
export interface backendInterface {
    createGoal(request: CreateGoalRequest): Promise<{
        __kind__: "ok";
        ok: GoalPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createObstacleTemplate(request: CreateObstacleRequest): Promise<ObstacleTemplate>;
    deleteCheckIn(checkInId: CheckInId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: {
            __kind__: "sealed";
            sealed: string;
        } | {
            __kind__: "notFound";
            notFound: null;
        } | {
            __kind__: "unauthorized";
            unauthorized: null;
        };
    }>;
    devReset(): Promise<void>;
    getAnalytics(): Promise<AnalyticsSummary>;
    getCheckInsForGoal(goalId: GoalId): Promise<Array<CheckIn>>;
    getCheckInsForGoalTimeline(goalId: GoalId, fromTimestamp: bigint): Promise<Array<CheckIn>>;
    getCheckInsForPeriod(goalId: GoalId, fromTimestamp: bigint, toTimestamp: bigint): Promise<Array<CheckIn>>;
    getGoal(goalId: GoalId): Promise<GoalPublic | null>;
    getInteractionCount(checkInId: CheckInId): Promise<bigint>;
    getMyProfile(): Promise<UserProfilePublic>;
    getPartnerFeed(): Promise<Array<FeedItem>>;
    getUserProfile(target: UserId): Promise<UserProfilePublic | null>;
    isUsernameAvailable(username: string): Promise<boolean>;
    listAllUsers(): Promise<Array<UserProfilePublic>>;
    listConnections(): Promise<Array<ConnectionPublic>>;
    listMyCheckIns(): Promise<Array<CheckIn>>;
    listMyGoals(): Promise<Array<GoalPublic>>;
    listMyObstacleTemplates(): Promise<Array<ObstacleTemplate>>;
    listPendingRequests(): Promise<Array<ConnectionPublic>>;
    recordCheckIn(request: RecordCheckInRequest): Promise<CheckIn>;
    recordInteraction(checkInId: CheckInId, interactionType: InteractionType): Promise<Interaction>;
    register(username: string): Promise<UserProfilePublic>;
    respondToConnection(connectionId: ConnectionId, accept: boolean): Promise<boolean>;
    sendConnectionRequest(target: UserId): Promise<ConnectionPublic>;
    setTimezone(tz: string): Promise<void>;
    updateGoal(goalId: GoalId, request: UpdateGoalRequest): Promise<{
        __kind__: "ok";
        ok: GoalPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateGoalState(goalId: GoalId, newState: GoalState): Promise<boolean>;
    updateMyProfile(displayName: string | null, avatarEmoji: string | null, bio: string | null, email: string | null): Promise<{
        __kind__: "ok";
        ok: UserProfilePublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { CheckIn as _CheckIn, CheckInId as _CheckInId, CheckInType as _CheckInType, ConnectionId as _ConnectionId, ConnectionPublic as _ConnectionPublic, ConnectionStatus as _ConnectionStatus, CreateGoalRequest as _CreateGoalRequest, FeedItem as _FeedItem, GoalId as _GoalId, GoalPublic as _GoalPublic, GoalState as _GoalState, Interaction as _Interaction, InteractionId as _InteractionId, InteractionType as _InteractionType, ObstacleTemplateId as _ObstacleTemplateId, RecordCheckInRequest as _RecordCheckInRequest, Timestamp as _Timestamp, UpdateGoalRequest as _UpdateGoalRequest, UserId as _UserId, UserProfilePublic as _UserProfilePublic, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createGoal(arg0: CreateGoalRequest): Promise<{
        __kind__: "ok";
        ok: GoalPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createGoal(to_candid_CreateGoalRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGoal(to_candid_CreateGoalRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createObstacleTemplate(arg0: CreateObstacleRequest): Promise<ObstacleTemplate> {
        if (this.processError) {
            try {
                const result = await this.actor.createObstacleTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createObstacleTemplate(arg0);
            return result;
        }
    }
    async deleteCheckIn(arg0: CheckInId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: {
            __kind__: "sealed";
            sealed: string;
        } | {
            __kind__: "notFound";
            notFound: null;
        } | {
            __kind__: "unauthorized";
            unauthorized: null;
        };
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCheckIn(arg0);
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCheckIn(arg0);
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async devReset(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.devReset();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.devReset();
            return result;
        }
    }
    async getAnalytics(): Promise<AnalyticsSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getCheckInsForGoal(arg0: GoalId): Promise<Array<CheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckInsForGoal(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckInsForGoal(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCheckInsForGoalTimeline(arg0: GoalId, arg1: bigint): Promise<Array<CheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckInsForGoalTimeline(arg0, arg1);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckInsForGoalTimeline(arg0, arg1);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCheckInsForPeriod(arg0: GoalId, arg1: bigint, arg2: bigint): Promise<Array<CheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckInsForPeriod(arg0, arg1, arg2);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckInsForPeriod(arg0, arg1, arg2);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGoal(arg0: GoalId): Promise<GoalPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoal(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoal(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInteractionCount(arg0: CheckInId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getInteractionCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInteractionCount(arg0);
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_UserProfilePublic_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_UserProfilePublic_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnerFeed(): Promise<Array<FeedItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerFeed();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerFeed();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isUsernameAvailable(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUsernameAvailable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUsernameAvailable(arg0);
            return result;
        }
    }
    async listAllUsers(): Promise<Array<UserProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async listConnections(): Promise<Array<ConnectionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listConnections();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listConnections();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyCheckIns(): Promise<Array<CheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyCheckIns();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyCheckIns();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyGoals(): Promise<Array<GoalPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyGoals();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyGoals();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyObstacleTemplates(): Promise<Array<ObstacleTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyObstacleTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyObstacleTemplates();
            return result;
        }
    }
    async listPendingRequests(): Promise<Array<ConnectionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingRequests();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingRequests();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordCheckIn(arg0: RecordCheckInRequest): Promise<CheckIn> {
        if (this.processError) {
            try {
                const result = await this.actor.recordCheckIn(to_candid_RecordCheckInRequest_n35(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CheckIn_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordCheckIn(to_candid_RecordCheckInRequest_n35(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CheckIn_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordInteraction(arg0: CheckInId, arg1: InteractionType): Promise<Interaction> {
        if (this.processError) {
            try {
                const result = await this.actor.recordInteraction(arg0, to_candid_InteractionType_n39(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Interaction_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordInteraction(arg0, to_candid_InteractionType_n39(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Interaction_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: string): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0);
                return from_candid_UserProfilePublic_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0);
            return from_candid_UserProfilePublic_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async respondToConnection(arg0: ConnectionId, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToConnection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToConnection(arg0, arg1);
            return result;
        }
    }
    async sendConnectionRequest(arg0: UserId): Promise<ConnectionPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.sendConnectionRequest(arg0);
                return from_candid_ConnectionPublic_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendConnectionRequest(arg0);
            return from_candid_ConnectionPublic_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async setTimezone(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTimezone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTimezone(arg0);
            return result;
        }
    }
    async updateGoal(arg0: GoalId, arg1: UpdateGoalRequest): Promise<{
        __kind__: "ok";
        ok: GoalPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoal(arg0, to_candid_UpdateGoalRequest_n45(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoal(arg0, to_candid_UpdateGoalRequest_n45(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGoalState(arg0: GoalId, arg1: GoalState): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoalState(arg0, to_candid_GoalState_n47(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoalState(arg0, to_candid_GoalState_n47(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMyProfile(arg0: string | null, arg1: string | null, arg2: string | null, arg3: string | null): Promise<{
        __kind__: "ok";
        ok: UserProfilePublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(to_candid_opt_n49(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg3));
                return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(to_candid_opt_n49(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg3));
            return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CheckInType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CheckInType): CheckInType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_CheckIn_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CheckIn): CheckIn {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ConnectionPublic_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConnectionPublic): ConnectionPublic {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_ConnectionStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConnectionStatus): ConnectionStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_FeedItem_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedItem): FeedItem {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_GoalPublic_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalPublic): GoalPublic {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_GoalState_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalState): GoalState {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_InteractionType_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InteractionType): InteractionType {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Interaction_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Interaction): Interaction {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ObstacleTemplateId]): ObstacleTemplateId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GoalPublic]): GoalPublic | null {
    return value.length === 0 ? null : from_candid_GoalPublic_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CheckInId;
    owner: _UserId;
    goalId: _GoalId;
    checkInType: _CheckInType;
    obstacleTemplateId: [] | [_ObstacleTemplateId];
    timestamp: _Timestamp;
    executedIfThen: boolean;
    lockInStartedAt: [] | [bigint];
    lockInEndedAt: [] | [bigint];
    customObstacleNote: [] | [string];
}): {
    id: CheckInId;
    owner: UserId;
    goalId: GoalId;
    checkInType: CheckInType;
    obstacleTemplateId?: ObstacleTemplateId;
    timestamp: Timestamp;
    executedIfThen: boolean;
    lockInStartedAt?: bigint;
    lockInEndedAt?: bigint;
    customObstacleNote?: string;
} {
    return {
        id: value.id,
        owner: value.owner,
        goalId: value.goalId,
        checkInType: from_candid_CheckInType_n17(_uploadFile, _downloadFile, value.checkInType),
        obstacleTemplateId: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.obstacleTemplateId)),
        timestamp: value.timestamp,
        executedIfThen: value.executedIfThen,
        lockInStartedAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.lockInStartedAt)),
        lockInEndedAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.lockInEndedAt)),
        customObstacleNote: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.customObstacleNote))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: [] | [string];
    timezone: string;
    username: string;
    displayName: string;
    role: _UserRole;
    email: [] | [string];
    avatarEmoji: string;
}): {
    id: UserId;
    bio?: string;
    timezone: string;
    username: string;
    displayName: string;
    role: UserRole;
    email?: string;
    avatarEmoji: string;
} {
    return {
        id: value.id,
        bio: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.bio)),
        timezone: value.timezone,
        username: value.username,
        displayName: value.displayName,
        role: from_candid_UserRole_n22(_uploadFile, _downloadFile, value.role),
        email: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.email)),
        avatarEmoji: value.avatarEmoji
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checkIn: _CheckIn;
    goalName: string;
    partnerDisplayName: string;
    highFiveCount: bigint;
}): {
    checkIn: CheckIn;
    goalName: string;
    partnerDisplayName: string;
    highFiveCount: bigint;
} {
    return {
        checkIn: from_candid_CheckIn_n15(_uploadFile, _downloadFile, value.checkIn),
        goalName: value.goalName,
        partnerDisplayName: value.partnerDisplayName,
        highFiveCount: value.highFiveCount
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ConnectionId;
    status: _ConnectionStatus;
    createdAt: _Timestamp;
    toPrincipal: _UserId;
    fromPrincipal: _UserId;
}): {
    id: ConnectionId;
    status: ConnectionStatus;
    createdAt: Timestamp;
    toPrincipal: UserId;
    fromPrincipal: UserId;
} {
    return {
        id: value.id,
        status: from_candid_ConnectionStatus_n32(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        toPrincipal: value.toPrincipal,
        fromPrincipal: value.fromPrincipal
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _InteractionId;
    interactionType: _InteractionType;
    fromPrincipal: _UserId;
    checkInId: _CheckInId;
    timestamp: _Timestamp;
}): {
    id: InteractionId;
    interactionType: InteractionType;
    fromPrincipal: UserId;
    checkInId: CheckInId;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        interactionType: from_candid_InteractionType_n43(_uploadFile, _downloadFile, value.interactionType),
        fromPrincipal: value.fromPrincipal,
        checkInId: value.checkInId,
        timestamp: value.timestamp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GoalId;
    startTime: [] | [string];
    emailNotifications: boolean;
    endTime: [] | [string];
    owner: _UserId;
    lastEditedAt: [] | [_Timestamp];
    createdAt: _Timestamp;
    wish: string;
    themeColor: [] | [string];
    wishDescription: string;
    iconName: [] | [string];
    ifThenPlan: string;
    updatedAt: _Timestamp;
    state: _GoalState;
    obstacleTemplateId: [] | [_ObstacleTemplateId];
    isLockIn: boolean;
    reminderOffset: [] | [bigint];
    intentTime: [] | [string];
    outcome: string;
}): {
    id: GoalId;
    startTime?: string;
    emailNotifications: boolean;
    endTime?: string;
    owner: UserId;
    lastEditedAt?: Timestamp;
    createdAt: Timestamp;
    wish: string;
    themeColor?: string;
    wishDescription: string;
    iconName?: string;
    ifThenPlan: string;
    updatedAt: Timestamp;
    state: GoalState;
    obstacleTemplateId?: ObstacleTemplateId;
    isLockIn: boolean;
    reminderOffset?: bigint;
    intentTime?: string;
    outcome: string;
} {
    return {
        id: value.id,
        startTime: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.startTime)),
        emailNotifications: value.emailNotifications,
        endTime: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.endTime)),
        owner: value.owner,
        lastEditedAt: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.lastEditedAt)),
        createdAt: value.createdAt,
        wish: value.wish,
        themeColor: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.themeColor)),
        wishDescription: value.wishDescription,
        iconName: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.iconName)),
        ifThenPlan: value.ifThenPlan,
        updatedAt: value.updatedAt,
        state: from_candid_GoalState_n8(_uploadFile, _downloadFile, value.state),
        obstacleTemplateId: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.obstacleTemplateId)),
        isLockIn: value.isLockIn,
        reminderOffset: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.reminderOffset)),
        intentTime: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.intentTime)),
        outcome: value.outcome
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: {
        sealed: string;
    } | {
        notFound: null;
    } | {
        unauthorized: null;
    };
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: {
        __kind__: "sealed";
        sealed: string;
    } | {
        __kind__: "notFound";
        notFound: null;
    } | {
        __kind__: "unauthorized";
        unauthorized: null;
    };
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_variant_n13(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sealed: string;
} | {
    notFound: null;
} | {
    unauthorized: null;
}): {
    __kind__: "sealed";
    sealed: string;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} {
    return "sealed" in value ? {
        __kind__: "sealed",
        sealed: value.sealed
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    skip: null;
} | {
    missedCheckIn: null;
} | {
    missedCheckOut: null;
} | {
    success: null;
} | {
    inProgress: null;
}): CheckInType {
    return "skip" in value ? CheckInType.skip : "missedCheckIn" in value ? CheckInType.missedCheckIn : "missedCheckOut" in value ? CheckInType.missedCheckOut : "success" in value ? CheckInType.success : "inProgress" in value ? CheckInType.inProgress : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GoalPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: GoalPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_GoalPublic_n4(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): ConnectionStatus {
    return "pending" in value ? ConnectionStatus.pending : "rejected" in value ? ConnectionStatus.rejected : "accepted" in value ? ConnectionStatus.accepted : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    highFive: null;
}): InteractionType {
    return "highFive" in value ? InteractionType.highFive : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfilePublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfilePublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfilePublic_n20(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
} | {
    abandoned: null;
} | {
    paused: null;
}): GoalState {
    return "active" in value ? GoalState.active : "completed" in value ? GoalState.completed : "abandoned" in value ? GoalState.abandoned : "paused" in value ? GoalState.paused : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CheckIn>): Array<CheckIn> {
    return value.map((x)=>from_candid_CheckIn_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeedItem>): Array<FeedItem> {
    return value.map((x)=>from_candid_FeedItem_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfilePublic>): Array<UserProfilePublic> {
    return value.map((x)=>from_candid_UserProfilePublic_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConnectionPublic>): Array<ConnectionPublic> {
    return value.map((x)=>from_candid_ConnectionPublic_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GoalPublic>): Array<GoalPublic> {
    return value.map((x)=>from_candid_GoalPublic_n4(_uploadFile, _downloadFile, x));
}
function to_candid_CheckInType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CheckInType): _CheckInType {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_CreateGoalRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateGoalRequest): _CreateGoalRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_GoalState_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalState): _GoalState {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid_InteractionType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InteractionType): _InteractionType {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_RecordCheckInRequest_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecordCheckInRequest): _RecordCheckInRequest {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateGoalRequest_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateGoalRequest): _UpdateGoalRequest {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime?: string;
    endTime?: string;
    wish: string;
    themeColor?: string;
    wishDescription: string;
    iconName?: string;
    ifThenPlan: string;
    obstacleTemplateId?: ObstacleTemplateId;
    isLockIn: boolean;
    outcome: string;
}): {
    startTime: [] | [string];
    endTime: [] | [string];
    wish: string;
    themeColor: [] | [string];
    wishDescription: string;
    iconName: [] | [string];
    ifThenPlan: string;
    obstacleTemplateId: [] | [_ObstacleTemplateId];
    isLockIn: boolean;
    outcome: string;
} {
    return {
        startTime: value.startTime ? candid_some(value.startTime) : candid_none(),
        endTime: value.endTime ? candid_some(value.endTime) : candid_none(),
        wish: value.wish,
        themeColor: value.themeColor ? candid_some(value.themeColor) : candid_none(),
        wishDescription: value.wishDescription,
        iconName: value.iconName ? candid_some(value.iconName) : candid_none(),
        ifThenPlan: value.ifThenPlan,
        obstacleTemplateId: value.obstacleTemplateId ? candid_some(value.obstacleTemplateId) : candid_none(),
        isLockIn: value.isLockIn,
        outcome: value.outcome
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timezoneOffsetMinutes: bigint;
    goalId: GoalId;
    checkInType: CheckInType;
    obstacleTemplateId?: ObstacleTemplateId;
    executedIfThen: boolean;
    lockInStartedAt?: bigint;
    lockInEndedAt?: bigint;
    customObstacleNote?: string;
}): {
    timezoneOffsetMinutes: bigint;
    goalId: _GoalId;
    checkInType: _CheckInType;
    obstacleTemplateId: [] | [_ObstacleTemplateId];
    executedIfThen: boolean;
    lockInStartedAt: [] | [bigint];
    lockInEndedAt: [] | [bigint];
    customObstacleNote: [] | [string];
} {
    return {
        timezoneOffsetMinutes: value.timezoneOffsetMinutes,
        goalId: value.goalId,
        checkInType: to_candid_CheckInType_n37(_uploadFile, _downloadFile, value.checkInType),
        obstacleTemplateId: value.obstacleTemplateId ? candid_some(value.obstacleTemplateId) : candid_none(),
        executedIfThen: value.executedIfThen,
        lockInStartedAt: value.lockInStartedAt ? candid_some(value.lockInStartedAt) : candid_none(),
        lockInEndedAt: value.lockInEndedAt ? candid_some(value.lockInEndedAt) : candid_none(),
        customObstacleNote: value.customObstacleNote ? candid_some(value.customObstacleNote) : candid_none()
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime?: string;
    emailNotifications?: boolean;
    endTime?: string;
    timezoneOffsetMinutes: bigint;
    wish?: string;
    themeColor?: string;
    wishDescription?: string;
    iconName?: string;
    ifThenPlan?: string;
    isLockIn?: boolean;
    reminderOffset?: bigint;
    intentTime?: string;
    outcome?: string;
}): {
    startTime: [] | [string];
    emailNotifications: [] | [boolean];
    endTime: [] | [string];
    timezoneOffsetMinutes: bigint;
    wish: [] | [string];
    themeColor: [] | [string];
    wishDescription: [] | [string];
    iconName: [] | [string];
    ifThenPlan: [] | [string];
    isLockIn: [] | [boolean];
    reminderOffset: [] | [bigint];
    intentTime: [] | [string];
    outcome: [] | [string];
} {
    return {
        startTime: value.startTime ? candid_some(value.startTime) : candid_none(),
        emailNotifications: value.emailNotifications ? candid_some(value.emailNotifications) : candid_none(),
        endTime: value.endTime ? candid_some(value.endTime) : candid_none(),
        timezoneOffsetMinutes: value.timezoneOffsetMinutes,
        wish: value.wish ? candid_some(value.wish) : candid_none(),
        themeColor: value.themeColor ? candid_some(value.themeColor) : candid_none(),
        wishDescription: value.wishDescription ? candid_some(value.wishDescription) : candid_none(),
        iconName: value.iconName ? candid_some(value.iconName) : candid_none(),
        ifThenPlan: value.ifThenPlan ? candid_some(value.ifThenPlan) : candid_none(),
        isLockIn: value.isLockIn ? candid_some(value.isLockIn) : candid_none(),
        reminderOffset: value.reminderOffset ? candid_some(value.reminderOffset) : candid_none(),
        intentTime: value.intentTime ? candid_some(value.intentTime) : candid_none(),
        outcome: value.outcome ? candid_some(value.outcome) : candid_none()
    };
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CheckInType): {
    skip: null;
} | {
    missedCheckIn: null;
} | {
    missedCheckOut: null;
} | {
    success: null;
} | {
    inProgress: null;
} {
    return value == CheckInType.skip ? {
        skip: null
    } : value == CheckInType.missedCheckIn ? {
        missedCheckIn: null
    } : value == CheckInType.missedCheckOut ? {
        missedCheckOut: null
    } : value == CheckInType.success ? {
        success: null
    } : value == CheckInType.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InteractionType): {
    highFive: null;
} {
    return value == InteractionType.highFive ? {
        highFive: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalState): {
    active: null;
} | {
    completed: null;
} | {
    abandoned: null;
} | {
    paused: null;
} {
    return value == GoalState.active ? {
        active: null
    } : value == GoalState.completed ? {
        completed: null
    } : value == GoalState.abandoned ? {
        abandoned: null
    } : value == GoalState.paused ? {
        paused: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
