/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface AnalyticsSummary {
    categoryBreakdown: Array<CategoryStat>;
    dayOfWeek: Array<DayOfWeekStat>;
    bestDayOfWeek?: bigint;
    overallIfThenEffectiveness: IfThenEffectiveness;
    habits: Array<HabitAnalytics>;
    worstDayOfWeek?: bigint;
}
export type AvatarColor = string | null;
export type AvatarShape = Variant_Star_Pentagon_Triangle_Hexagon_Square | null;
export interface CategoryStat {
    successes: bigint;
    total: bigint;
    rate: number;
    category: GoalCategory;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface CheckIn {
    id: CheckInId;
    owner: UserId;
    note?: string;
    goalId: GoalId;
    checkInType: CheckInType;
    obstacleTemplateId?: ObstacleTemplateId;
    timestamp: Timestamp;
    executedIfThen: boolean;
    lockInStartedAt?: bigint;
    lockInEndedAt?: bigint;
}
export type CheckInId = bigint;
export type ConnectionId = bigint;
export interface ConnectionPublic {
    id: ConnectionId;
    status: ConnectionStatus;
    createdAt: Timestamp;
    toPrincipal: UserId;
    fromPrincipal: UserId;
}
export interface CreateHabitRequest {
    startTime?: string;
    endTimeMinutes?: bigint;
    endTime?: string;
    scheduledDays?: Array<string>;
    startTimeMinutes?: bigint;
    goalId: GoalId;
    themeColor?: string;
    wishDescription?: string;
    ifThenPlan: string;
    obstacleTemplateId?: ObstacleTemplateId;
    isLockIn: boolean;
    lockInDurationMinutes?: bigint;
}
export interface CreateMacroGoalRequest {
    wish: string;
    wishDescription: string;
    category: GoalCategory;
    outcome: string;
}
export interface DayOfWeekStat {
    successes: bigint;
    total: bigint;
    dayOfWeek: bigint;
    rate: number;
    dayName: string;
}
export interface FeedItem {
    checkIn: CheckIn;
    goalName: string;
    partnerDisplayName: string;
    partnerAvatarColor: AvatarColor;
    highFiveCount: bigint;
    partnerAvatarColorMode: AvatarColorMode;
    partnerAvatarShape: AvatarShape;
}
export interface FollowThroughRate {
    successes: bigint;
    total: bigint;
    rate: number;
}
export type GoalId = bigint;
export interface GoalWithHabitsPublic {
    goal: MacroGoalPublic;
    habits: Array<HabitPublic>;
}
export interface HabitAnalytics {
    ifThenEffectiveness: IfThenEffectiveness;
    predictedObstacle?: ObstacleStat;
    habitName: string;
    habitId: GoalId;
    actualObstacles: Array<ObstacleStat>;
    shownUpDays: bigint;
    category: GoalCategory;
}
export interface HabitPublic {
    id: GoalId;
    startTime?: string;
    endTimeMinutes: bigint;
    endTime?: string;
    scheduledDays: Array<string>;
    owner: UserId;
    lastEditedAt?: Timestamp;
    startTimeMinutes: bigint;
    createdAt: Timestamp;
    wish: string;
    goalId: GoalId;
    themeColor?: string;
    wishDescription: string;
    ifThenPlan: string;
    updatedAt: Timestamp;
    state: GoalState;
    obstacleTemplateId?: ObstacleTemplateId;
    category: GoalCategory;
    isLockIn: boolean;
    outcome: string;
    lockInDurationMinutes: bigint;
}
export interface IfThenEffectiveness {
    notUsedPlan: FollowThroughRate;
    usedPlan: FollowThroughRate;
}
export interface Interaction {
    id: InteractionId;
    interactionType: InteractionType;
    fromPrincipal: UserId;
    checkInId: CheckInId;
    timestamp: Timestamp;
}
export type InteractionId = bigint;
export interface MacroGoalPublic {
    id: GoalId;
    owner: UserId;
    createdAt: Timestamp;
    wish: string;
    wishDescription: string;
    updatedAt: Timestamp;
    state: GoalState;
    category: GoalCategory;
    outcome: string;
}
export interface ObstacleStat {
    obstacleName: string;
    count: bigint;
    obstacleTemplateId?: ObstacleTemplateId;
}
export interface ObstacleTemplate {
    id: ObstacleTemplateId;
    title: string;
    owner: UserId;
    description: string;
}
export type ObstacleTemplateId = bigint;
export interface PartnerHabitDetail {
    habits: Array<HabitPublic>;
    profile: UserProfilePublic;
}
export interface PartnerOverview {
    activeHabitCount: bigint;
    profile: UserProfilePublic;
    currentStreak: bigint;
}
export interface RecordCheckInRequest {
    timezoneOffsetMinutes: bigint;
    note?: string;
    goalId: GoalId;
    checkInType: CheckInType;
    obstacleTemplateId?: ObstacleTemplateId;
    executedIfThen: boolean;
    lockInStartedAt?: bigint;
    lockInEndedAt?: bigint;
}
export interface ResolveObstacleRequest {
    labelText: string;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface ReusableGoalPublic {
    id: GoalId;
    wish: string;
    wishDescription: string;
    state: GoalState;
    category: GoalCategory;
}
export type Timestamp = bigint;
export interface UpdateHabitRequest {
    startTime?: string;
    endTimeMinutes?: bigint;
    endTime?: string;
    scheduledDays?: Array<string>;
    timezoneOffsetMinutes: bigint;
    startTimeMinutes?: bigint;
    themeColor?: string;
    isTimeEdit?: boolean;
    ifThenPlan?: string;
    obstacleTemplateId?: ObstacleTemplateId;
    isLockIn?: boolean;
    lockInDurationMinutes?: bigint;
}
export interface UpdateMacroGoalRequest {
}
export type UserId = Principal;
export interface UserProfilePublic {
    id: UserId;
    bio?: string;
    timezone: string;
    username: string;
    displayName: string;
    timezoneOffsetMinutes: bigint;
    role: UserRole;
    email?: string;
    avatarColor: AvatarColor;
    avatarColorMode: AvatarColorMode;
    avatarShape: AvatarShape;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum AvatarColorMode {
    Fill = "Fill",
    BorderOnly = "BorderOnly"
}
export enum CheckInType {
    skip = "skip",
    missed = "missed",
    missedCheckIn = "missedCheckIn",
    missedCheckOut = "missedCheckOut",
    success = "success",
    inProgress = "inProgress"
}
export enum ConnectionStatus {
    pending = "pending",
    rejected = "rejected",
    accepted = "accepted"
}
export enum GoalCategory {
    Productivity = "Productivity",
    Learning = "Learning",
    Health = "Health",
    Social = "Social",
    Leisure = "Leisure"
}
export enum GoalState {
    active = "active",
    completed = "completed",
    paused = "paused"
}
export enum InteractionType {
    highFive = "highFive"
}
export enum PartnerHabitError {
    notPartner = "notPartner",
    profileNotFound = "profileNotFound"
}
export enum UserRole {
    admin = "admin",
    user = "user"
}
export enum Variant_Star_Pentagon_Triangle_Hexagon_Square {
    Star = "Star",
    Pentagon = "Pentagon",
    Triangle = "Triangle",
    Hexagon = "Hexagon",
    Square = "Square"
}
export enum Variant_notFound_unauthorized {
    notFound = "notFound",
    unauthorized = "unauthorized"
}
export interface backendInterface {
    /**
     * / Create a habit inside an existing macro goal. `request.goalId` is
     * / REQUIRED — the habit must reference an existing macro goal owned by the
     * / caller. The habit inherits the parent's category; wish/outcome are
     * / sourced from the parent and read-only. The habit's wishDescription
     * / (displayed name) defaults to the parent's, but is overridden by
     * / `request.wishDescription` when the caller supplies one.
     */
    createHabit(request: CreateHabitRequest): Promise<{
        __kind__: "ok";
        ok: HabitPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    /**
     * / Create a macro goal (a container). Captured by the goal wizard:
     * / category, wish, outcome (wishDescription). Does NOT accept Lock-In or
     * / schedule fields.
     */
    createMacroGoal(request: CreateMacroGoalRequest): Promise<{
        __kind__: "ok";
        ok: MacroGoalPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteCheckIn(checkInId: CheckInId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: {
            __kind__: "sealed";
            sealed: string;
        } | {
            __kind__: "notFound";
            notFound: null;
        } | {
            __kind__: "unauthorized";
            unauthorized: null;
        };
    }>;
    /**
     * / Permanently delete a macro goal and all of its child habits in a single
     * / atomic operation. Removes every child habit's check-ins, timeline
     * / entries, and feed interactions before removing the habits and the goal
     * / itself. All-or-nothing: partial failure cannot leave dangling habits.
     * / Hard-delete is final — no soft-delete or recoverable state.
     */
    deleteGoal(goalId: GoalId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    /**
     * / Permanently delete a single habit in one atomic operation. Removes the
     * / habit's check-ins, timeline entries, and feed interactions before
     * / removing the habit itself. All-or-nothing: partial failure cannot leave
     * / dangling check-ins. Hard-delete is final — no soft-delete or recoverable
     * / state. Scoped to one habit — does not touch the parent macro goal or
     * / sibling habits.
     */
    deleteHabit(habitId: GoalId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    devReset(): Promise<void>;
    execute(qJson: string): Promise<Result>;
    getAnalytics(timezoneOffsetMinutes: bigint): Promise<AnalyticsSummary>;
    getApiDoc(): Promise<string>;
    getCheckInsForGoal(goalId: GoalId): Promise<Array<CheckIn>>;
    getCheckInsForGoalTimeline(goalId: GoalId, fromTimestamp: bigint): Promise<Array<CheckIn>>;
    getCheckInsForPeriod(goalId: GoalId, fromTimestamp: bigint, toTimestamp: bigint): Promise<Array<CheckIn>>;
    /**
     * / Retrieve a habit by ID. Only the owning caller can see it.
     */
    getHabit(habitId: GoalId): Promise<HabitPublic | null>;
    getInteractionCount(checkInId: CheckInId): Promise<bigint>;
    /**
     * / Retrieve a macro goal by ID. Only the owning caller can see it.
     */
    getMacroGoal(goalId: GoalId): Promise<MacroGoalPublic | null>;
    getMyProfile(): Promise<UserProfilePublic>;
    getPartnerFeed(): Promise<Array<FeedItem>>;
    /**
     * / Returns the full habit detail for a single partner. Returns #notPartner
     * / for any non-partner, pending-only, or unconnected caller — no habit data
     * / leaks.
     */
    getPartnerHabits(target: Principal): Promise<{
        __kind__: "ok";
        ok: PartnerHabitDetail;
    } | {
        __kind__: "err";
        err: PartnerHabitError;
    }>;
    getUserProfile(target: UserId): Promise<UserProfilePublic | null>;
    isUsernameAvailable(username: string): Promise<boolean>;
    listAllUsers(): Promise<Array<UserProfilePublic>>;
    listConnections(): Promise<Array<ConnectionPublic>>;
    /**
     * / List habits linked to a specific macro goal (by parent goalId).
     */
    listHabitsByParent(parentGoalId: GoalId): Promise<{
        __kind__: "ok";
        ok: Array<HabitPublic>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    listMyCheckIns(): Promise<Array<CheckIn>>;
    /**
     * / List the caller's macro goals, each grouped with its linked habits.
     * / Supports the dashboard grouping requirement.
     */
    listMyGoals(): Promise<Array<GoalWithHabitsPublic>>;
    /**
     * / Returns the caller's reusable macro goals for the wizard chips.
     * / Each entry exposes id, wish, wishDescription, state, and category.
     */
    listMyReusableGoals(): Promise<Array<ReusableGoalPublic>>;
    /**
     * / Returns an overview row for every accepted, mutual partner of the
     * / caller. Each row has the partner's profile, active habit count, and
     * / current streak. Pending requests and non-partners are never included.
     */
    listPartnerOverviews(): Promise<Array<PartnerOverview>>;
    listPendingRequests(): Promise<Array<ConnectionPublic>>;
    markCheckInIfThenUsed(checkInId: CheckInId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: Variant_notFound_unauthorized;
    }>;
    recordCheckIn(request: RecordCheckInRequest): Promise<CheckIn>;
    recordInteraction(checkInId: CheckInId, interactionType: InteractionType): Promise<Interaction>;
    register(username: string): Promise<UserProfilePublic>;
    /**
     * / Resolves a built-in obstacle label to one of the seven fixed built-in
     * / obstacles. The match is case-insensitive on the built-in title. If the
     * / label is not one of the seven built-ins, the call traps — a custom
     * / obstacle can never be created. Returns the matching built-in
     * / `ObstacleTemplate` with its stable id.
     */
    resolveObstacleLabel(request: ResolveObstacleRequest): Promise<ObstacleTemplate>;
    respondToConnection(connectionId: ConnectionId, accept: boolean): Promise<boolean>;
    schema(): Promise<string>;
    sendConnectionRequest(target: UserId): Promise<ConnectionPublic>;
    setTimezone(tz: string): Promise<void>;
    /**
     * / Transition a goal (macro or habit) to a new state.
     */
    updateGoalState(goalId: GoalId, newState: GoalState): Promise<boolean>;
    /**
     * / Update an editable habit. wish/wishDescription/outcome/category are
     * / immutable (sourced from the parent macro goal).
     */
    updateHabit(habitId: GoalId, request: UpdateHabitRequest): Promise<{
        __kind__: "ok";
        ok: HabitPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    /**
     * / Update an editable macro goal. Only cosmetic fields are editable;
     * / wish/wishDescription/outcome/category are immutable after creation.
     */
    updateMacroGoal(goalId: GoalId, request: UpdateMacroGoalRequest): Promise<{
        __kind__: "ok";
        ok: MacroGoalPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateMyProfile(displayName: string | null, avatarShape: AvatarShape, avatarColor: AvatarColor, avatarColorMode: AvatarColorMode | null, bio: string | null, email: string | null, timezoneOffsetMinutes: bigint | null): Promise<{
        __kind__: "ok";
        ok: UserProfilePublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { AnalyticsSummary as _AnalyticsSummary, AvatarColor as _AvatarColor, AvatarColorMode as _AvatarColorMode, AvatarShape as _AvatarShape, CategoryStat as _CategoryStat, Cell as _Cell, CheckIn as _CheckIn, CheckInId as _CheckInId, CheckInType as _CheckInType, ConnectionId as _ConnectionId, ConnectionPublic as _ConnectionPublic, ConnectionStatus as _ConnectionStatus, CreateHabitRequest as _CreateHabitRequest, CreateMacroGoalRequest as _CreateMacroGoalRequest, DayOfWeekStat as _DayOfWeekStat, FeedItem as _FeedItem, GoalCategory as _GoalCategory, GoalId as _GoalId, GoalState as _GoalState, GoalWithHabitsPublic as _GoalWithHabitsPublic, HabitAnalytics as _HabitAnalytics, HabitPublic as _HabitPublic, IfThenEffectiveness as _IfThenEffectiveness, Interaction as _Interaction, InteractionId as _InteractionId, InteractionType as _InteractionType, MacroGoalPublic as _MacroGoalPublic, ObstacleStat as _ObstacleStat, ObstacleTemplateId as _ObstacleTemplateId, PartnerHabitDetail as _PartnerHabitDetail, PartnerHabitError as _PartnerHabitError, PartnerOverview as _PartnerOverview, RecordCheckInRequest as _RecordCheckInRequest, Result as _Result, ReusableGoalPublic as _ReusableGoalPublic, Timestamp as _Timestamp, UpdateHabitRequest as _UpdateHabitRequest, UserId as _UserId, UserProfilePublic as _UserProfilePublic, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createHabit(arg0: CreateHabitRequest): Promise<{
        __kind__: "ok";
        ok: HabitPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createHabit(to_candid_CreateHabitRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHabit(to_candid_CreateHabitRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createMacroGoal(arg0: CreateMacroGoalRequest): Promise<{
        __kind__: "ok";
        ok: MacroGoalPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createMacroGoal(to_candid_CreateMacroGoalRequest_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMacroGoal(to_candid_CreateMacroGoalRequest_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCheckIn(arg0: CheckInId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: {
            __kind__: "sealed";
            sealed: string;
        } | {
            __kind__: "notFound";
            notFound: null;
        } | {
            __kind__: "unauthorized";
            unauthorized: null;
        };
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCheckIn(arg0);
                return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCheckIn(arg0);
            return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteGoal(arg0: GoalId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGoal(arg0);
                return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGoal(arg0);
            return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteHabit(arg0: GoalId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHabit(arg0);
                return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHabit(arg0);
            return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async devReset(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.devReset();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.devReset();
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalytics(arg0: bigint): Promise<AnalyticsSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics(arg0);
                return from_candid_AnalyticsSummary_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics(arg0);
            return from_candid_AnalyticsSummary_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCheckInsForGoal(arg0: GoalId): Promise<Array<CheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckInsForGoal(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckInsForGoal(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCheckInsForGoalTimeline(arg0: GoalId, arg1: bigint): Promise<Array<CheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckInsForGoalTimeline(arg0, arg1);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckInsForGoalTimeline(arg0, arg1);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCheckInsForPeriod(arg0: GoalId, arg1: bigint, arg2: bigint): Promise<Array<CheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckInsForPeriod(arg0, arg1, arg2);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckInsForPeriod(arg0, arg1, arg2);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHabit(arg0: GoalId): Promise<HabitPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabit(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabit(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInteractionCount(arg0: CheckInId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getInteractionCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInteractionCount(arg0);
            return result;
        }
    }
    async getMacroGoal(arg0: GoalId): Promise<MacroGoalPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMacroGoal(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMacroGoal(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_UserProfilePublic_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_UserProfilePublic_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnerFeed(): Promise<Array<FeedItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerFeed();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerFeed();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnerHabits(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: PartnerHabitDetail;
    } | {
        __kind__: "err";
        err: PartnerHabitError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerHabits(arg0);
                return from_candid_variant_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerHabits(arg0);
            return from_candid_variant_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async isUsernameAvailable(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUsernameAvailable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUsernameAvailable(arg0);
            return result;
        }
    }
    async listAllUsers(): Promise<Array<UserProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async listConnections(): Promise<Array<ConnectionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listConnections();
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listConnections();
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async listHabitsByParent(arg0: GoalId): Promise<{
        __kind__: "ok";
        ok: Array<HabitPublic>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.listHabitsByParent(arg0);
                return from_candid_variant_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listHabitsByParent(arg0);
            return from_candid_variant_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyCheckIns(): Promise<Array<CheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyCheckIns();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyCheckIns();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyGoals(): Promise<Array<GoalWithHabitsPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyGoals();
                return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyGoals();
            return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyReusableGoals(): Promise<Array<ReusableGoalPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyReusableGoals();
                return from_candid_vec_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyReusableGoals();
            return from_candid_vec_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPartnerOverviews(): Promise<Array<PartnerOverview>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPartnerOverviews();
                return from_candid_vec_n77(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPartnerOverviews();
            return from_candid_vec_n77(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPendingRequests(): Promise<Array<ConnectionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingRequests();
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingRequests();
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async markCheckInIfThenUsed(arg0: CheckInId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: Variant_notFound_unauthorized;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.markCheckInIfThenUsed(arg0);
                return from_candid_variant_n80(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markCheckInIfThenUsed(arg0);
            return from_candid_variant_n80(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordCheckIn(arg0: RecordCheckInRequest): Promise<CheckIn> {
        if (this.processError) {
            try {
                const result = await this.actor.recordCheckIn(to_candid_RecordCheckInRequest_n82(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CheckIn_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordCheckIn(to_candid_RecordCheckInRequest_n82(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CheckIn_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordInteraction(arg0: CheckInId, arg1: InteractionType): Promise<Interaction> {
        if (this.processError) {
            try {
                const result = await this.actor.recordInteraction(arg0, to_candid_InteractionType_n85(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Interaction_n86(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordInteraction(arg0, to_candid_InteractionType_n85(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Interaction_n86(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: string): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0);
                return from_candid_UserProfilePublic_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0);
            return from_candid_UserProfilePublic_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async resolveObstacleLabel(arg0: ResolveObstacleRequest): Promise<ObstacleTemplate> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveObstacleLabel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveObstacleLabel(arg0);
            return result;
        }
    }
    async respondToConnection(arg0: ConnectionId, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToConnection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToConnection(arg0, arg1);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async sendConnectionRequest(arg0: UserId): Promise<ConnectionPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.sendConnectionRequest(arg0);
                return from_candid_ConnectionPublic_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendConnectionRequest(arg0);
            return from_candid_ConnectionPublic_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async setTimezone(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTimezone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTimezone(arg0);
            return result;
        }
    }
    async updateGoalState(arg0: GoalId, arg1: GoalState): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoalState(arg0, to_candid_GoalState_n89(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoalState(arg0, to_candid_GoalState_n89(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateHabit(arg0: GoalId, arg1: UpdateHabitRequest): Promise<{
        __kind__: "ok";
        ok: HabitPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHabit(arg0, to_candid_UpdateHabitRequest_n90(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHabit(arg0, to_candid_UpdateHabitRequest_n90(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMacroGoal(arg0: GoalId, arg1: UpdateMacroGoalRequest): Promise<{
        __kind__: "ok";
        ok: MacroGoalPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMacroGoal(arg0, arg1);
                return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMacroGoal(arg0, arg1);
            return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMyProfile(arg0: string | null, arg1: AvatarShape, arg2: AvatarColor, arg3: AvatarColorMode | null, arg4: string | null, arg5: string | null, arg6: bigint | null): Promise<{
        __kind__: "ok";
        ok: UserProfilePublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(to_candid_opt_n92(this._uploadFile, this._downloadFile, arg0), to_candid_AvatarShape_n93(this._uploadFile, this._downloadFile, arg1), to_candid_AvatarColor_n96(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n97(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n92(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n92(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n99(this._uploadFile, this._downloadFile, arg6));
                return from_candid_variant_n100(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(to_candid_opt_n92(this._uploadFile, this._downloadFile, arg0), to_candid_AvatarShape_n93(this._uploadFile, this._downloadFile, arg1), to_candid_AvatarColor_n96(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n97(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n92(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n92(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n99(this._uploadFile, this._downloadFile, arg6));
            return from_candid_variant_n100(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AnalyticsSummary_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalyticsSummary): AnalyticsSummary {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_AvatarColorMode_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvatarColorMode): AvatarColorMode {
    return "Fill" in value ? AvatarColorMode.Fill : "BorderOnly" in value ? AvatarColorMode.BorderOnly : value;
}
function from_candid_AvatarColor_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvatarColor): AvatarColor {
    return from_candid_opt_n6(_uploadFile, _downloadFile, value);
}
function from_candid_AvatarShape_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvatarShape): AvatarShape {
    return from_candid_opt_n54(_uploadFile, _downloadFile, value);
}
function from_candid_CategoryStat_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryStat): CategoryStat {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_CheckInType_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CheckInType): CheckInType {
    return "skip" in value ? CheckInType.skip : "missed" in value ? CheckInType.missed : "missedCheckIn" in value ? CheckInType.missedCheckIn : "missedCheckOut" in value ? CheckInType.missedCheckOut : "success" in value ? CheckInType.success : "inProgress" in value ? CheckInType.inProgress : value;
}
function from_candid_CheckIn_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CheckIn): CheckIn {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_ConnectionPublic_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConnectionPublic): ConnectionPublic {
    return from_candid_record_n68(_uploadFile, _downloadFile, value);
}
function from_candid_ConnectionStatus_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConnectionStatus): ConnectionStatus {
    return "pending" in value ? ConnectionStatus.pending : "rejected" in value ? ConnectionStatus.rejected : "accepted" in value ? ConnectionStatus.accepted : value;
}
function from_candid_FeedItem_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedItem): FeedItem {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_GoalCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalCategory): GoalCategory {
    return "Productivity" in value ? GoalCategory.Productivity : "Learning" in value ? GoalCategory.Learning : "Health" in value ? GoalCategory.Health : "Social" in value ? GoalCategory.Social : "Leisure" in value ? GoalCategory.Leisure : value;
}
function from_candid_GoalState_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalState): GoalState {
    return "active" in value ? GoalState.active : "completed" in value ? GoalState.completed : "paused" in value ? GoalState.paused : value;
}
function from_candid_GoalWithHabitsPublic_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalWithHabitsPublic): GoalWithHabitsPublic {
    return from_candid_record_n73(_uploadFile, _downloadFile, value);
}
function from_candid_HabitAnalytics_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HabitAnalytics): HabitAnalytics {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_HabitPublic_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HabitPublic): HabitPublic {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_InteractionType_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InteractionType): InteractionType {
    return "highFive" in value ? InteractionType.highFive : value;
}
function from_candid_Interaction_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Interaction): Interaction {
    return from_candid_record_n87(_uploadFile, _downloadFile, value);
}
function from_candid_MacroGoalPublic_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MacroGoalPublic): MacroGoalPublic {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ObstacleStat_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ObstacleStat): ObstacleStat {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_PartnerHabitDetail_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PartnerHabitDetail): PartnerHabitDetail {
    return from_candid_record_n61(_uploadFile, _downloadFile, value);
}
function from_candid_PartnerHabitError_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PartnerHabitError): PartnerHabitError {
    return "notPartner" in value ? PartnerHabitError.notPartner : "profileNotFound" in value ? PartnerHabitError.profileNotFound : value;
}
function from_candid_PartnerOverview_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PartnerOverview): PartnerOverview {
    return from_candid_record_n79(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ReusableGoalPublic_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReusableGoalPublic): ReusableGoalPublic {
    return from_candid_record_n76(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : value;
}
function from_candid_Value_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ObstacleStat]): ObstacleStat | null {
    return value.length === 0 ? null : from_candid_ObstacleStat_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HabitPublic]): HabitPublic | null {
    return value.length === 0 ? null : from_candid_HabitPublic_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MacroGoalPublic]): MacroGoalPublic | null {
    return value.length === 0 ? null : from_candid_MacroGoalPublic_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        Star: null;
    } | {
        Pentagon: null;
    } | {
        Triangle: null;
    } | {
        Hexagon: null;
    } | {
        Square: null;
    }]): Variant_Star_Pentagon_Triangle_Hexagon_Square | null {
    return value.length === 0 ? null : from_candid_variant_n55(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ObstacleTemplateId]): ObstacleTemplateId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GoalId;
    owner: _UserId;
    createdAt: _Timestamp;
    wish: string;
    wishDescription: string;
    updatedAt: _Timestamp;
    state: _GoalState;
    category: _GoalCategory;
    outcome: string;
}): {
    id: GoalId;
    owner: UserId;
    createdAt: Timestamp;
    wish: string;
    wishDescription: string;
    updatedAt: Timestamp;
    state: GoalState;
    category: GoalCategory;
    outcome: string;
} {
    return {
        id: value.id,
        owner: value.owner,
        createdAt: value.createdAt,
        wish: value.wish,
        wishDescription: value.wishDescription,
        updatedAt: value.updatedAt,
        state: from_candid_GoalState_n8(_uploadFile, _downloadFile, value.state),
        category: from_candid_GoalCategory_n10(_uploadFile, _downloadFile, value.category),
        outcome: value.outcome
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n22(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n26(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categoryBreakdown: Array<_CategoryStat>;
    dayOfWeek: Array<_DayOfWeekStat>;
    bestDayOfWeek: [] | [bigint];
    overallIfThenEffectiveness: _IfThenEffectiveness;
    habits: Array<_HabitAnalytics>;
    worstDayOfWeek: [] | [bigint];
}): {
    categoryBreakdown: Array<CategoryStat>;
    dayOfWeek: Array<DayOfWeekStat>;
    bestDayOfWeek?: bigint;
    overallIfThenEffectiveness: IfThenEffectiveness;
    habits: Array<HabitAnalytics>;
    worstDayOfWeek?: bigint;
} {
    return {
        categoryBreakdown: from_candid_vec_n30(_uploadFile, _downloadFile, value.categoryBreakdown),
        dayOfWeek: value.dayOfWeek,
        bestDayOfWeek: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.bestDayOfWeek)),
        overallIfThenEffectiveness: value.overallIfThenEffectiveness,
        habits: from_candid_vec_n34(_uploadFile, _downloadFile, value.habits),
        worstDayOfWeek: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.worstDayOfWeek))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    successes: bigint;
    total: bigint;
    rate: number;
    category: _GoalCategory;
}): {
    successes: bigint;
    total: bigint;
    rate: number;
    category: GoalCategory;
} {
    return {
        successes: value.successes,
        total: value.total,
        rate: value.rate,
        category: from_candid_GoalCategory_n10(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ifThenEffectiveness: _IfThenEffectiveness;
    predictedObstacle: [] | [_ObstacleStat];
    habitName: string;
    habitId: _GoalId;
    actualObstacles: Array<_ObstacleStat>;
    shownUpDays: bigint;
    category: _GoalCategory;
}): {
    ifThenEffectiveness: IfThenEffectiveness;
    predictedObstacle?: ObstacleStat;
    habitName: string;
    habitId: GoalId;
    actualObstacles: Array<ObstacleStat>;
    shownUpDays: bigint;
    category: GoalCategory;
} {
    return {
        ifThenEffectiveness: value.ifThenEffectiveness,
        predictedObstacle: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.predictedObstacle)),
        habitName: value.habitName,
        habitId: value.habitId,
        actualObstacles: from_candid_vec_n40(_uploadFile, _downloadFile, value.actualObstacles),
        shownUpDays: value.shownUpDays,
        category: from_candid_GoalCategory_n10(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    obstacleName: string;
    count: bigint;
    obstacleTemplateId: [] | [_ObstacleTemplateId];
}): {
    obstacleName: string;
    count: bigint;
    obstacleTemplateId?: ObstacleTemplateId;
} {
    return {
        obstacleName: value.obstacleName,
        count: value.count,
        obstacleTemplateId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.obstacleTemplateId))
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CheckInId;
    owner: _UserId;
    note: [] | [string];
    goalId: _GoalId;
    checkInType: _CheckInType;
    obstacleTemplateId: [] | [_ObstacleTemplateId];
    timestamp: _Timestamp;
    executedIfThen: boolean;
    lockInStartedAt: [] | [bigint];
    lockInEndedAt: [] | [bigint];
}): {
    id: CheckInId;
    owner: UserId;
    note?: string;
    goalId: GoalId;
    checkInType: CheckInType;
    obstacleTemplateId?: ObstacleTemplateId;
    timestamp: Timestamp;
    executedIfThen: boolean;
    lockInStartedAt?: bigint;
    lockInEndedAt?: bigint;
} {
    return {
        id: value.id,
        owner: value.owner,
        note: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.note)),
        goalId: value.goalId,
        checkInType: from_candid_CheckInType_n44(_uploadFile, _downloadFile, value.checkInType),
        obstacleTemplateId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.obstacleTemplateId)),
        timestamp: value.timestamp,
        executedIfThen: value.executedIfThen,
        lockInStartedAt: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.lockInStartedAt)),
        lockInEndedAt: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.lockInEndedAt))
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: [] | [string];
    timezone: string;
    username: string;
    displayName: string;
    timezoneOffsetMinutes: bigint;
    role: _UserRole;
    email: [] | [string];
    avatarColor: _AvatarColor;
    avatarColorMode: _AvatarColorMode;
    avatarShape: _AvatarShape;
}): {
    id: UserId;
    bio?: string;
    timezone: string;
    username: string;
    displayName: string;
    timezoneOffsetMinutes: bigint;
    role: UserRole;
    email?: string;
    avatarColor: AvatarColor;
    avatarColorMode: AvatarColorMode;
    avatarShape: AvatarShape;
} {
    return {
        id: value.id,
        bio: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.bio)),
        timezone: value.timezone,
        username: value.username,
        displayName: value.displayName,
        timezoneOffsetMinutes: value.timezoneOffsetMinutes,
        role: from_candid_UserRole_n50(_uploadFile, _downloadFile, value.role),
        email: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.email)),
        avatarColor: from_candid_AvatarColor_n51(_uploadFile, _downloadFile, value.avatarColor),
        avatarColorMode: from_candid_AvatarColorMode_n52(_uploadFile, _downloadFile, value.avatarColorMode),
        avatarShape: from_candid_AvatarShape_n53(_uploadFile, _downloadFile, value.avatarShape)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GoalId;
    startTime: [] | [string];
    endTimeMinutes: bigint;
    endTime: [] | [string];
    scheduledDays: Array<string>;
    owner: _UserId;
    lastEditedAt: [] | [_Timestamp];
    startTimeMinutes: bigint;
    createdAt: _Timestamp;
    wish: string;
    goalId: _GoalId;
    themeColor: [] | [string];
    wishDescription: string;
    ifThenPlan: string;
    updatedAt: _Timestamp;
    state: _GoalState;
    obstacleTemplateId: [] | [_ObstacleTemplateId];
    category: _GoalCategory;
    isLockIn: boolean;
    outcome: string;
    lockInDurationMinutes: bigint;
}): {
    id: GoalId;
    startTime?: string;
    endTimeMinutes: bigint;
    endTime?: string;
    scheduledDays: Array<string>;
    owner: UserId;
    lastEditedAt?: Timestamp;
    startTimeMinutes: bigint;
    createdAt: Timestamp;
    wish: string;
    goalId: GoalId;
    themeColor?: string;
    wishDescription: string;
    ifThenPlan: string;
    updatedAt: Timestamp;
    state: GoalState;
    obstacleTemplateId?: ObstacleTemplateId;
    category: GoalCategory;
    isLockIn: boolean;
    outcome: string;
    lockInDurationMinutes: bigint;
} {
    return {
        id: value.id,
        startTime: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.startTime)),
        endTimeMinutes: value.endTimeMinutes,
        endTime: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.endTime)),
        scheduledDays: value.scheduledDays,
        owner: value.owner,
        lastEditedAt: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.lastEditedAt)),
        startTimeMinutes: value.startTimeMinutes,
        createdAt: value.createdAt,
        wish: value.wish,
        goalId: value.goalId,
        themeColor: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.themeColor)),
        wishDescription: value.wishDescription,
        ifThenPlan: value.ifThenPlan,
        updatedAt: value.updatedAt,
        state: from_candid_GoalState_n8(_uploadFile, _downloadFile, value.state),
        obstacleTemplateId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.obstacleTemplateId)),
        category: from_candid_GoalCategory_n10(_uploadFile, _downloadFile, value.category),
        isLockIn: value.isLockIn,
        outcome: value.outcome,
        lockInDurationMinutes: value.lockInDurationMinutes
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checkIn: _CheckIn;
    goalName: string;
    partnerDisplayName: string;
    partnerAvatarColor: _AvatarColor;
    highFiveCount: bigint;
    partnerAvatarColorMode: _AvatarColorMode;
    partnerAvatarShape: _AvatarShape;
}): {
    checkIn: CheckIn;
    goalName: string;
    partnerDisplayName: string;
    partnerAvatarColor: AvatarColor;
    highFiveCount: bigint;
    partnerAvatarColorMode: AvatarColorMode;
    partnerAvatarShape: AvatarShape;
} {
    return {
        checkIn: from_candid_CheckIn_n42(_uploadFile, _downloadFile, value.checkIn),
        goalName: value.goalName,
        partnerDisplayName: value.partnerDisplayName,
        partnerAvatarColor: from_candid_AvatarColor_n51(_uploadFile, _downloadFile, value.partnerAvatarColor),
        highFiveCount: value.highFiveCount,
        partnerAvatarColorMode: from_candid_AvatarColorMode_n52(_uploadFile, _downloadFile, value.partnerAvatarColorMode),
        partnerAvatarShape: from_candid_AvatarShape_n53(_uploadFile, _downloadFile, value.partnerAvatarShape)
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    habits: Array<_HabitPublic>;
    profile: _UserProfilePublic;
}): {
    habits: Array<HabitPublic>;
    profile: UserProfilePublic;
} {
    return {
        habits: from_candid_vec_n62(_uploadFile, _downloadFile, value.habits),
        profile: from_candid_UserProfilePublic_n48(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ConnectionId;
    status: _ConnectionStatus;
    createdAt: _Timestamp;
    toPrincipal: _UserId;
    fromPrincipal: _UserId;
}): {
    id: ConnectionId;
    status: ConnectionStatus;
    createdAt: Timestamp;
    toPrincipal: UserId;
    fromPrincipal: UserId;
} {
    return {
        id: value.id,
        status: from_candid_ConnectionStatus_n69(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        toPrincipal: value.toPrincipal,
        fromPrincipal: value.fromPrincipal
    };
}
function from_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goal: _MacroGoalPublic;
    habits: Array<_HabitPublic>;
}): {
    goal: MacroGoalPublic;
    habits: Array<HabitPublic>;
} {
    return {
        goal: from_candid_MacroGoalPublic_n15(_uploadFile, _downloadFile, value.goal),
        habits: from_candid_vec_n62(_uploadFile, _downloadFile, value.habits)
    };
}
function from_candid_record_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GoalId;
    wish: string;
    wishDescription: string;
    state: _GoalState;
    category: _GoalCategory;
}): {
    id: GoalId;
    wish: string;
    wishDescription: string;
    state: GoalState;
    category: GoalCategory;
} {
    return {
        id: value.id,
        wish: value.wish,
        wishDescription: value.wishDescription,
        state: from_candid_GoalState_n8(_uploadFile, _downloadFile, value.state),
        category: from_candid_GoalCategory_n10(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activeHabitCount: bigint;
    profile: _UserProfilePublic;
    currentStreak: bigint;
}): {
    activeHabitCount: bigint;
    profile: UserProfilePublic;
    currentStreak: bigint;
} {
    return {
        activeHabitCount: value.activeHabitCount,
        profile: from_candid_UserProfilePublic_n48(_uploadFile, _downloadFile, value.profile),
        currentStreak: value.currentStreak
    };
}
function from_candid_record_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _InteractionId;
    interactionType: _InteractionType;
    fromPrincipal: _UserId;
    checkInId: _CheckInId;
    timestamp: _Timestamp;
}): {
    id: InteractionId;
    interactionType: InteractionType;
    fromPrincipal: UserId;
    checkInId: CheckInId;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        interactionType: from_candid_InteractionType_n88(_uploadFile, _downloadFile, value.interactionType),
        fromPrincipal: value.fromPrincipal,
        checkInId: value.checkInId,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n100(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfilePublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfilePublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfilePublic_n48(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _MacroGoalPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: MacroGoalPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_MacroGoalPublic_n15(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: {
        sealed: string;
    } | {
        notFound: null;
    } | {
        unauthorized: null;
    };
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: {
        __kind__: "sealed";
        sealed: string;
    } | {
        __kind__: "notFound";
        notFound: null;
    } | {
        __kind__: "unauthorized";
        unauthorized: null;
    };
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_variant_n18(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sealed: string;
} | {
    notFound: null;
} | {
    unauthorized: null;
}): {
    __kind__: "sealed";
    sealed: string;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} {
    return "sealed" in value ? {
        __kind__: "sealed",
        sealed: value.sealed
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _HabitPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: HabitPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_HabitPublic_n4(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Star: null;
} | {
    Pentagon: null;
} | {
    Triangle: null;
} | {
    Hexagon: null;
} | {
    Square: null;
}): Variant_Star_Pentagon_Triangle_Hexagon_Square {
    return "Star" in value ? Variant_Star_Pentagon_Triangle_Hexagon_Square.Star : "Pentagon" in value ? Variant_Star_Pentagon_Triangle_Hexagon_Square.Pentagon : "Triangle" in value ? Variant_Star_Pentagon_Triangle_Hexagon_Square.Triangle : "Hexagon" in value ? Variant_Star_Pentagon_Triangle_Hexagon_Square.Hexagon : "Square" in value ? Variant_Star_Pentagon_Triangle_Hexagon_Square.Square : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PartnerHabitDetail;
} | {
    err: _PartnerHabitError;
}): {
    __kind__: "ok";
    ok: PartnerHabitDetail;
} | {
    __kind__: "err";
    err: PartnerHabitError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PartnerHabitDetail_n60(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_PartnerHabitError_n63(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_HabitPublic>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<HabitPublic>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n62(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: {
        notFound: null;
    } | {
        unauthorized: null;
    };
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Variant_notFound_unauthorized;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_variant_n81(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notFound: null;
} | {
    unauthorized: null;
}): Variant_notFound_unauthorized {
    return "notFound" in value ? Variant_notFound_unauthorized.notFound : "unauthorized" in value ? Variant_notFound_unauthorized.unauthorized : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CategoryStat>): Array<CategoryStat> {
    return value.map((x)=>from_candid_CategoryStat_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HabitAnalytics>): Array<HabitAnalytics> {
    return value.map((x)=>from_candid_HabitAnalytics_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ObstacleStat>): Array<ObstacleStat> {
    return value.map((x)=>from_candid_ObstacleStat_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CheckIn>): Array<CheckIn> {
    return value.map((x)=>from_candid_CheckIn_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeedItem>): Array<FeedItem> {
    return value.map((x)=>from_candid_FeedItem_n57(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HabitPublic>): Array<HabitPublic> {
    return value.map((x)=>from_candid_HabitPublic_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfilePublic>): Array<UserProfilePublic> {
    return value.map((x)=>from_candid_UserProfilePublic_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConnectionPublic>): Array<ConnectionPublic> {
    return value.map((x)=>from_candid_ConnectionPublic_n67(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GoalWithHabitsPublic>): Array<GoalWithHabitsPublic> {
    return value.map((x)=>from_candid_GoalWithHabitsPublic_n72(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReusableGoalPublic>): Array<ReusableGoalPublic> {
    return value.map((x)=>from_candid_ReusableGoalPublic_n75(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PartnerOverview>): Array<PartnerOverview> {
    return value.map((x)=>from_candid_PartnerOverview_n78(_uploadFile, _downloadFile, x));
}
function to_candid_AvatarColorMode_n98(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvatarColorMode): _AvatarColorMode {
    return value == AvatarColorMode.Fill ? {
        Fill: null
    } : value == AvatarColorMode.BorderOnly ? {
        BorderOnly: null
    } : value;
}
function to_candid_AvatarColor_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvatarColor): _AvatarColor {
    return to_candid_opt_n92(_uploadFile, _downloadFile, value);
}
function to_candid_AvatarShape_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvatarShape): _AvatarShape {
    return to_candid_opt_n94(_uploadFile, _downloadFile, value);
}
function to_candid_CheckInType_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CheckInType): _CheckInType {
    return value == CheckInType.skip ? {
        skip: null
    } : value == CheckInType.missed ? {
        missed: null
    } : value == CheckInType.missedCheckIn ? {
        missedCheckIn: null
    } : value == CheckInType.missedCheckOut ? {
        missedCheckOut: null
    } : value == CheckInType.success ? {
        success: null
    } : value == CheckInType.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_CreateHabitRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateHabitRequest): _CreateHabitRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateMacroGoalRequest_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateMacroGoalRequest): _CreateMacroGoalRequest {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_GoalCategory_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalCategory): _GoalCategory {
    return value == GoalCategory.Productivity ? {
        Productivity: null
    } : value == GoalCategory.Learning ? {
        Learning: null
    } : value == GoalCategory.Health ? {
        Health: null
    } : value == GoalCategory.Social ? {
        Social: null
    } : value == GoalCategory.Leisure ? {
        Leisure: null
    } : value;
}
function to_candid_GoalState_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalState): _GoalState {
    return value == GoalState.active ? {
        active: null
    } : value == GoalState.completed ? {
        completed: null
    } : value == GoalState.paused ? {
        paused: null
    } : value;
}
function to_candid_InteractionType_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InteractionType): _InteractionType {
    return value == InteractionType.highFive ? {
        highFive: null
    } : value;
}
function to_candid_RecordCheckInRequest_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecordCheckInRequest): _RecordCheckInRequest {
    return to_candid_record_n83(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateHabitRequest_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateHabitRequest): _UpdateHabitRequest {
    return to_candid_record_n91(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_Star_Pentagon_Triangle_Hexagon_Square | null): [] | [{
        Star: null;
    } | {
        Pentagon: null;
    } | {
        Triangle: null;
    } | {
        Hexagon: null;
    } | {
        Square: null;
    }] {
    return value === null ? candid_none() : candid_some(to_candid_variant_n95(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvatarColorMode | null): [] | [_AvatarColorMode] {
    return value === null ? candid_none() : candid_some(to_candid_AvatarColorMode_n98(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n99(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wish: string;
    wishDescription: string;
    category: GoalCategory;
    outcome: string;
}): {
    wish: string;
    wishDescription: string;
    category: _GoalCategory;
    outcome: string;
} {
    return {
        wish: value.wish,
        wishDescription: value.wishDescription,
        category: to_candid_GoalCategory_n13(_uploadFile, _downloadFile, value.category),
        outcome: value.outcome
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime?: string;
    endTimeMinutes?: bigint;
    endTime?: string;
    scheduledDays?: Array<string>;
    startTimeMinutes?: bigint;
    goalId: GoalId;
    themeColor?: string;
    wishDescription?: string;
    ifThenPlan: string;
    obstacleTemplateId?: ObstacleTemplateId;
    isLockIn: boolean;
    lockInDurationMinutes?: bigint;
}): {
    startTime: [] | [string];
    endTimeMinutes: [] | [bigint];
    endTime: [] | [string];
    scheduledDays: [] | [Array<string>];
    startTimeMinutes: [] | [bigint];
    goalId: _GoalId;
    themeColor: [] | [string];
    wishDescription: [] | [string];
    ifThenPlan: string;
    obstacleTemplateId: [] | [_ObstacleTemplateId];
    isLockIn: boolean;
    lockInDurationMinutes: [] | [bigint];
} {
    return {
        startTime: value.startTime ? candid_some(value.startTime) : candid_none(),
        endTimeMinutes: value.endTimeMinutes ? candid_some(value.endTimeMinutes) : candid_none(),
        endTime: value.endTime ? candid_some(value.endTime) : candid_none(),
        scheduledDays: value.scheduledDays ? candid_some(value.scheduledDays) : candid_none(),
        startTimeMinutes: value.startTimeMinutes ? candid_some(value.startTimeMinutes) : candid_none(),
        goalId: value.goalId,
        themeColor: value.themeColor ? candid_some(value.themeColor) : candid_none(),
        wishDescription: value.wishDescription ? candid_some(value.wishDescription) : candid_none(),
        ifThenPlan: value.ifThenPlan,
        obstacleTemplateId: value.obstacleTemplateId ? candid_some(value.obstacleTemplateId) : candid_none(),
        isLockIn: value.isLockIn,
        lockInDurationMinutes: value.lockInDurationMinutes ? candid_some(value.lockInDurationMinutes) : candid_none()
    };
}
function to_candid_record_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timezoneOffsetMinutes: bigint;
    note?: string;
    goalId: GoalId;
    checkInType: CheckInType;
    obstacleTemplateId?: ObstacleTemplateId;
    executedIfThen: boolean;
    lockInStartedAt?: bigint;
    lockInEndedAt?: bigint;
}): {
    timezoneOffsetMinutes: bigint;
    note: [] | [string];
    goalId: _GoalId;
    checkInType: _CheckInType;
    obstacleTemplateId: [] | [_ObstacleTemplateId];
    executedIfThen: boolean;
    lockInStartedAt: [] | [bigint];
    lockInEndedAt: [] | [bigint];
} {
    return {
        timezoneOffsetMinutes: value.timezoneOffsetMinutes,
        note: value.note ? candid_some(value.note) : candid_none(),
        goalId: value.goalId,
        checkInType: to_candid_CheckInType_n84(_uploadFile, _downloadFile, value.checkInType),
        obstacleTemplateId: value.obstacleTemplateId ? candid_some(value.obstacleTemplateId) : candid_none(),
        executedIfThen: value.executedIfThen,
        lockInStartedAt: value.lockInStartedAt ? candid_some(value.lockInStartedAt) : candid_none(),
        lockInEndedAt: value.lockInEndedAt ? candid_some(value.lockInEndedAt) : candid_none()
    };
}
function to_candid_record_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime?: string;
    endTimeMinutes?: bigint;
    endTime?: string;
    scheduledDays?: Array<string>;
    timezoneOffsetMinutes: bigint;
    startTimeMinutes?: bigint;
    themeColor?: string;
    isTimeEdit?: boolean;
    ifThenPlan?: string;
    obstacleTemplateId?: ObstacleTemplateId;
    isLockIn?: boolean;
    lockInDurationMinutes?: bigint;
}): {
    startTime: [] | [string];
    endTimeMinutes: [] | [bigint];
    endTime: [] | [string];
    scheduledDays: [] | [Array<string>];
    timezoneOffsetMinutes: bigint;
    startTimeMinutes: [] | [bigint];
    themeColor: [] | [string];
    isTimeEdit: [] | [boolean];
    ifThenPlan: [] | [string];
    obstacleTemplateId: [] | [_ObstacleTemplateId];
    isLockIn: [] | [boolean];
    lockInDurationMinutes: [] | [bigint];
} {
    return {
        startTime: value.startTime ? candid_some(value.startTime) : candid_none(),
        endTimeMinutes: value.endTimeMinutes ? candid_some(value.endTimeMinutes) : candid_none(),
        endTime: value.endTime ? candid_some(value.endTime) : candid_none(),
        scheduledDays: value.scheduledDays ? candid_some(value.scheduledDays) : candid_none(),
        timezoneOffsetMinutes: value.timezoneOffsetMinutes,
        startTimeMinutes: value.startTimeMinutes ? candid_some(value.startTimeMinutes) : candid_none(),
        themeColor: value.themeColor ? candid_some(value.themeColor) : candid_none(),
        isTimeEdit: value.isTimeEdit ? candid_some(value.isTimeEdit) : candid_none(),
        ifThenPlan: value.ifThenPlan ? candid_some(value.ifThenPlan) : candid_none(),
        obstacleTemplateId: value.obstacleTemplateId ? candid_some(value.obstacleTemplateId) : candid_none(),
        isLockIn: value.isLockIn ? candid_some(value.isLockIn) : candid_none(),
        lockInDurationMinutes: value.lockInDurationMinutes ? candid_some(value.lockInDurationMinutes) : candid_none()
    };
}
function to_candid_variant_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_Star_Pentagon_Triangle_Hexagon_Square): {
    Star: null;
} | {
    Pentagon: null;
} | {
    Triangle: null;
} | {
    Hexagon: null;
} | {
    Square: null;
} {
    return value == Variant_Star_Pentagon_Triangle_Hexagon_Square.Star ? {
        Star: null
    } : value == Variant_Star_Pentagon_Triangle_Hexagon_Square.Pentagon ? {
        Pentagon: null
    } : value == Variant_Star_Pentagon_Triangle_Hexagon_Square.Triangle ? {
        Triangle: null
    } : value == Variant_Star_Pentagon_Triangle_Hexagon_Square.Hexagon ? {
        Hexagon: null
    } : value == Variant_Star_Pentagon_Triangle_Hexagon_Square.Square ? {
        Square: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
